CREATE SCHEMA IF NOT EXISTS v4_l1;
CREATE EXTENSION IF NOT EXISTS ltree;
DO $$ BEGIN
    CREATE TYPE v4_l1.lifecycle_state AS ENUM ('DRAFT', 'ACTIVE', 'SUSPENDED', 'ARCHIVED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
