/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CustomerPortalRouteImport } from './routes/customer-portal'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as TrackTokenRouteImport } from './routes/track.$token'
import { Route as JoinSlugRouteImport } from './routes/join.$slug'
import { Route as AppTodayRouteImport } from './routes/_app/today'
import { Route as AppSystemHealthRouteImport } from './routes/_app/system-health'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppServicesRouteImport } from './routes/_app/services'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppReceivablesRouteImport } from './routes/_app/receivables'
import { Route as AppOpsRouteImport } from './routes/_app/ops'
import { Route as AppManagerRouteImport } from './routes/_app/manager'
import { Route as AppLiveMapRouteImport } from './routes/_app/live-map'
import { Route as AppLedgerRouteImport } from './routes/_app/ledger'
import { Route as AppInventoryRouteImport } from './routes/_app/inventory'
import { Route as AppFinanceRouteImport } from './routes/_app/finance'
import { Route as AppDriverRouteImport } from './routes/_app/driver'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCustomersRouteImport } from './routes/_app/customers'
import { Route as AppCsRouteImport } from './routes/_app/cs'
import { Route as AppCrmRouteImport } from './routes/_app/crm'
import { Route as AppCashClosingRouteImport } from './routes/_app/cash-closing'
import { Route as AppBudgetsRouteImport } from './routes/_app/budgets'
import { Route as AppBranchesRouteImport } from './routes/_app/branches'
import { Route as AppBillingRouteImport } from './routes/_app/billing'
import { Route as AppAccountingRouteImport } from './routes/_app/accounting'
import { Route as AppStaffIndexRouteImport } from './routes/_app/staff/index'
import { Route as AppPickupsIndexRouteImport } from './routes/_app/pickups/index'
import { Route as AppOrdersIndexRouteImport } from './routes/_app/orders/index'
import { Route as AppStationsReceptionRouteImport } from './routes/_app/stations/reception'
import { Route as AppStationsQcRouteImport } from './routes/_app/stations/qc'
import { Route as AppStationsPackingRouteImport } from './routes/_app/stations/packing'
import { Route as AppStationsIroningRouteImport } from './routes/_app/stations/ironing'
import { Route as AppStationsDeliveryRouteImport } from './routes/_app/stations/delivery'
import { Route as AppStationsCleaningRouteImport } from './routes/_app/stations/cleaning'
import { Route as AppStaffUsersRouteImport } from './routes/_app/staff/users'
import { Route as AppStaffScheduleRouteImport } from './routes/_app/staff/schedule'
import { Route as AppStaffSalariesRouteImport } from './routes/_app/staff/salaries'
import { Route as AppStaffRequestsRouteImport } from './routes/_app/staff/requests'
import { Route as AppStaffNewRouteImport } from './routes/_app/staff/new'
import { Route as AppStaffLeavesRouteImport } from './routes/_app/staff/leaves'
import { Route as AppStaffIroningPayrollRouteImport } from './routes/_app/staff/ironing-payroll'
import { Route as AppStaffIdRouteImport } from './routes/_app/staff/$id'
import { Route as AppPickupsNewRouteImport } from './routes/_app/pickups/new'
import { Route as AppOrdersNewRouteImport } from './routes/_app/orders/new'
import { Route as AppOrdersIdRouteImport } from './routes/_app/orders/$id'
import { Route as AppBranchesIdRouteImport } from './routes/_app/branches/$id'
import { Route as AppAdminPlatformFeesRouteImport } from './routes/_app/admin/platform-fees'
import { Route as AppAdminBillingRouteImport } from './routes/_app/admin/billing'
import { Route as AppAdminUsersIndexRouteImport } from './routes/_app/admin/users/index'
import { Route as AppAdminTenantsIndexRouteImport } from './routes/_app/admin/tenants/index'
import { Route as AppAdminTenantsIdRouteImport } from './routes/_app/admin/tenants/$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerPortalRoute = CustomerPortalRouteImport.update({
  id: '/customer-portal',
  path: '/customer-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const TrackTokenRoute = TrackTokenRouteImport.update({
  id: '/track/$token',
  path: '/track/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinSlugRoute = JoinSlugRouteImport.update({
  id: '/join/$slug',
  path: '/join/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTodayRoute = AppTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemHealthRoute = AppSystemHealthRouteImport.update({
  id: '/system-health',
  path: '/system-health',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesRoute = AppServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppReceivablesRoute = AppReceivablesRouteImport.update({
  id: '/receivables',
  path: '/receivables',
  getParentRoute: () => AppRoute,
} as any)
const AppOpsRoute = AppOpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => AppRoute,
} as any)
const AppManagerRoute = AppManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => AppRoute,
} as any)
const AppLiveMapRoute = AppLiveMapRouteImport.update({
  id: '/live-map',
  path: '/live-map',
  getParentRoute: () => AppRoute,
} as any)
const AppLedgerRoute = AppLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppDriverRoute = AppDriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppCsRoute = AppCsRouteImport.update({
  id: '/cs',
  path: '/cs',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppCashClosingRoute = AppCashClosingRouteImport.update({
  id: '/cash-closing',
  path: '/cash-closing',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetsRoute = AppBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => AppRoute,
} as any)
const AppBranchesRoute = AppBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountingRoute = AppAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffIndexRoute = AppStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => AppRoute,
} as any)
const AppPickupsIndexRoute = AppPickupsIndexRouteImport.update({
  id: '/pickups/',
  path: '/pickups/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIndexRoute = AppOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AppRoute,
} as any)
const AppStationsReceptionRoute = AppStationsReceptionRouteImport.update({
  id: '/stations/reception',
  path: '/stations/reception',
  getParentRoute: () => AppRoute,
} as any)
const AppStationsQcRoute = AppStationsQcRouteImport.update({
  id: '/stations/qc',
  path: '/stations/qc',
  getParentRoute: () => AppRoute,
} as any)
const AppStationsPackingRoute = AppStationsPackingRouteImport.update({
  id: '/stations/packing',
  path: '/stations/packing',
  getParentRoute: () => AppRoute,
} as any)
const AppStationsIroningRoute = AppStationsIroningRouteImport.update({
  id: '/stations/ironing',
  path: '/stations/ironing',
  getParentRoute: () => AppRoute,
} as any)
const AppStationsDeliveryRoute = AppStationsDeliveryRouteImport.update({
  id: '/stations/delivery',
  path: '/stations/delivery',
  getParentRoute: () => AppRoute,
} as any)
const AppStationsCleaningRoute = AppStationsCleaningRouteImport.update({
  id: '/stations/cleaning',
  path: '/stations/cleaning',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffUsersRoute = AppStaffUsersRouteImport.update({
  id: '/staff/users',
  path: '/staff/users',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffScheduleRoute = AppStaffScheduleRouteImport.update({
  id: '/staff/schedule',
  path: '/staff/schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffSalariesRoute = AppStaffSalariesRouteImport.update({
  id: '/staff/salaries',
  path: '/staff/salaries',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffRequestsRoute = AppStaffRequestsRouteImport.update({
  id: '/staff/requests',
  path: '/staff/requests',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffNewRoute = AppStaffNewRouteImport.update({
  id: '/staff/new',
  path: '/staff/new',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffLeavesRoute = AppStaffLeavesRouteImport.update({
  id: '/staff/leaves',
  path: '/staff/leaves',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffIroningPayrollRoute = AppStaffIroningPayrollRouteImport.update({
  id: '/staff/ironing-payroll',
  path: '/staff/ironing-payroll',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffIdRoute = AppStaffIdRouteImport.update({
  id: '/staff/$id',
  path: '/staff/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPickupsNewRoute = AppPickupsNewRouteImport.update({
  id: '/pickups/new',
  path: '/pickups/new',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersNewRoute = AppOrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIdRoute = AppOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppBranchesIdRoute = AppBranchesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppBranchesRoute,
} as any)
const AppAdminPlatformFeesRoute = AppAdminPlatformFeesRouteImport.update({
  id: '/admin/platform-fees',
  path: '/admin/platform-fees',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminBillingRoute = AppAdminBillingRouteImport.update({
  id: '/admin/billing',
  path: '/admin/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersIndexRoute = AppAdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminTenantsIndexRoute = AppAdminTenantsIndexRouteImport.update({
  id: '/admin/tenants/',
  path: '/admin/tenants/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminTenantsIdRoute = AppAdminTenantsIdRouteImport.update({
  id: '/admin/tenants/$id',
  path: '/admin/tenants/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$slug': typeof SlugRoute
  '/': typeof AppIndexRoute
  '/customer-portal': typeof CustomerPortalRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/accounting': typeof AppAccountingRoute
  '/billing': typeof AppBillingRoute
  '/branches': typeof AppBranchesRouteWithChildren
  '/budgets': typeof AppBudgetsRoute
  '/cash-closing': typeof AppCashClosingRoute
  '/crm': typeof AppCrmRoute
  '/cs': typeof AppCsRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/driver': typeof AppDriverRoute
  '/finance': typeof AppFinanceRoute
  '/inventory': typeof AppInventoryRoute
  '/ledger': typeof AppLedgerRoute
  '/live-map': typeof AppLiveMapRoute
  '/manager': typeof AppManagerRoute
  '/ops': typeof AppOpsRoute
  '/receivables': typeof AppReceivablesRoute
  '/reports': typeof AppReportsRoute
  '/services': typeof AppServicesRoute
  '/settings': typeof AppSettingsRoute
  '/system-health': typeof AppSystemHealthRoute
  '/today': typeof AppTodayRoute
  '/join/$slug': typeof JoinSlugRoute
  '/track/$token': typeof TrackTokenRoute
  '/admin/billing': typeof AppAdminBillingRoute
  '/admin/platform-fees': typeof AppAdminPlatformFeesRoute
  '/branches/$id': typeof AppBranchesIdRoute
  '/orders/$id': typeof AppOrdersIdRoute
  '/orders/new': typeof AppOrdersNewRoute
  '/pickups/new': typeof AppPickupsNewRoute
  '/staff/$id': typeof AppStaffIdRoute
  '/staff/ironing-payroll': typeof AppStaffIroningPayrollRoute
  '/staff/leaves': typeof AppStaffLeavesRoute
  '/staff/new': typeof AppStaffNewRoute
  '/staff/requests': typeof AppStaffRequestsRoute
  '/staff/salaries': typeof AppStaffSalariesRoute
  '/staff/schedule': typeof AppStaffScheduleRoute
  '/staff/users': typeof AppStaffUsersRoute
  '/stations/cleaning': typeof AppStationsCleaningRoute
  '/stations/delivery': typeof AppStationsDeliveryRoute
  '/stations/ironing': typeof AppStationsIroningRoute
  '/stations/packing': typeof AppStationsPackingRoute
  '/stations/qc': typeof AppStationsQcRoute
  '/stations/reception': typeof AppStationsReceptionRoute
  '/orders/': typeof AppOrdersIndexRoute
  '/pickups/': typeof AppPickupsIndexRoute
  '/staff/': typeof AppStaffIndexRoute
  '/admin/tenants/$id': typeof AppAdminTenantsIdRoute
  '/admin/tenants/': typeof AppAdminTenantsIndexRoute
  '/admin/users/': typeof AppAdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/$slug': typeof SlugRoute
  '/customer-portal': typeof CustomerPortalRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/accounting': typeof AppAccountingRoute
  '/billing': typeof AppBillingRoute
  '/branches': typeof AppBranchesRouteWithChildren
  '/budgets': typeof AppBudgetsRoute
  '/cash-closing': typeof AppCashClosingRoute
  '/crm': typeof AppCrmRoute
  '/cs': typeof AppCsRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/driver': typeof AppDriverRoute
  '/finance': typeof AppFinanceRoute
  '/inventory': typeof AppInventoryRoute
  '/ledger': typeof AppLedgerRoute
  '/live-map': typeof AppLiveMapRoute
  '/manager': typeof AppManagerRoute
  '/ops': typeof AppOpsRoute
  '/receivables': typeof AppReceivablesRoute
  '/reports': typeof AppReportsRoute
  '/services': typeof AppServicesRoute
  '/settings': typeof AppSettingsRoute
  '/system-health': typeof AppSystemHealthRoute
  '/today': typeof AppTodayRoute
  '/join/$slug': typeof JoinSlugRoute
  '/track/$token': typeof TrackTokenRoute
  '/': typeof AppIndexRoute
  '/admin/billing': typeof AppAdminBillingRoute
  '/admin/platform-fees': typeof AppAdminPlatformFeesRoute
  '/branches/$id': typeof AppBranchesIdRoute
  '/orders/$id': typeof AppOrdersIdRoute
  '/orders/new': typeof AppOrdersNewRoute
  '/pickups/new': typeof AppPickupsNewRoute
  '/staff/$id': typeof AppStaffIdRoute
  '/staff/ironing-payroll': typeof AppStaffIroningPayrollRoute
  '/staff/leaves': typeof AppStaffLeavesRoute
  '/staff/new': typeof AppStaffNewRoute
  '/staff/requests': typeof AppStaffRequestsRoute
  '/staff/salaries': typeof AppStaffSalariesRoute
  '/staff/schedule': typeof AppStaffScheduleRoute
  '/staff/users': typeof AppStaffUsersRoute
  '/stations/cleaning': typeof AppStationsCleaningRoute
  '/stations/delivery': typeof AppStationsDeliveryRoute
  '/stations/ironing': typeof AppStationsIroningRoute
  '/stations/packing': typeof AppStationsPackingRoute
  '/stations/qc': typeof AppStationsQcRoute
  '/stations/reception': typeof AppStationsReceptionRoute
  '/orders': typeof AppOrdersIndexRoute
  '/pickups': typeof AppPickupsIndexRoute
  '/staff': typeof AppStaffIndexRoute
  '/admin/tenants/$id': typeof AppAdminTenantsIdRoute
  '/admin/tenants': typeof AppAdminTenantsIndexRoute
  '/admin/users': typeof AppAdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$slug': typeof SlugRoute
  '/_app': typeof AppRouteWithChildren
  '/customer-portal': typeof CustomerPortalRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/accounting': typeof AppAccountingRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/branches': typeof AppBranchesRouteWithChildren
  '/_app/budgets': typeof AppBudgetsRoute
  '/_app/cash-closing': typeof AppCashClosingRoute
  '/_app/crm': typeof AppCrmRoute
  '/_app/cs': typeof AppCsRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/driver': typeof AppDriverRoute
  '/_app/finance': typeof AppFinanceRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/ledger': typeof AppLedgerRoute
  '/_app/live-map': typeof AppLiveMapRoute
  '/_app/manager': typeof AppManagerRoute
  '/_app/ops': typeof AppOpsRoute
  '/_app/receivables': typeof AppReceivablesRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/services': typeof AppServicesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/system-health': typeof AppSystemHealthRoute
  '/_app/today': typeof AppTodayRoute
  '/join/$slug': typeof JoinSlugRoute
  '/track/$token': typeof TrackTokenRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/billing': typeof AppAdminBillingRoute
  '/_app/admin/platform-fees': typeof AppAdminPlatformFeesRoute
  '/_app/branches/$id': typeof AppBranchesIdRoute
  '/_app/orders/$id': typeof AppOrdersIdRoute
  '/_app/orders/new': typeof AppOrdersNewRoute
  '/_app/pickups/new': typeof AppPickupsNewRoute
  '/_app/staff/$id': typeof AppStaffIdRoute
  '/_app/staff/ironing-payroll': typeof AppStaffIroningPayrollRoute
  '/_app/staff/leaves': typeof AppStaffLeavesRoute
  '/_app/staff/new': typeof AppStaffNewRoute
  '/_app/staff/requests': typeof AppStaffRequestsRoute
  '/_app/staff/salaries': typeof AppStaffSalariesRoute
  '/_app/staff/schedule': typeof AppStaffScheduleRoute
  '/_app/staff/users': typeof AppStaffUsersRoute
  '/_app/stations/cleaning': typeof AppStationsCleaningRoute
  '/_app/stations/delivery': typeof AppStationsDeliveryRoute
  '/_app/stations/ironing': typeof AppStationsIroningRoute
  '/_app/stations/packing': typeof AppStationsPackingRoute
  '/_app/stations/qc': typeof AppStationsQcRoute
  '/_app/stations/reception': typeof AppStationsReceptionRoute
  '/_app/orders/': typeof AppOrdersIndexRoute
  '/_app/pickups/': typeof AppPickupsIndexRoute
  '/_app/staff/': typeof AppStaffIndexRoute
  '/_app/admin/tenants/$id': typeof AppAdminTenantsIdRoute
  '/_app/admin/tenants/': typeof AppAdminTenantsIndexRoute
  '/_app/admin/users/': typeof AppAdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$slug'
    | '/'
    | '/customer-portal'
    | '/login'
    | '/reset-password'
    | '/accounting'
    | '/billing'
    | '/branches'
    | '/budgets'
    | '/cash-closing'
    | '/crm'
    | '/cs'
    | '/customers'
    | '/dashboard'
    | '/driver'
    | '/finance'
    | '/inventory'
    | '/ledger'
    | '/live-map'
    | '/manager'
    | '/ops'
    | '/receivables'
    | '/reports'
    | '/services'
    | '/settings'
    | '/system-health'
    | '/today'
    | '/join/$slug'
    | '/track/$token'
    | '/admin/billing'
    | '/admin/platform-fees'
    | '/branches/$id'
    | '/orders/$id'
    | '/orders/new'
    | '/pickups/new'
    | '/staff/$id'
    | '/staff/ironing-payroll'
    | '/staff/leaves'
    | '/staff/new'
    | '/staff/requests'
    | '/staff/salaries'
    | '/staff/schedule'
    | '/staff/users'
    | '/stations/cleaning'
    | '/stations/delivery'
    | '/stations/ironing'
    | '/stations/packing'
    | '/stations/qc'
    | '/stations/reception'
    | '/orders/'
    | '/pickups/'
    | '/staff/'
    | '/admin/tenants/$id'
    | '/admin/tenants/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$slug'
    | '/customer-portal'
    | '/login'
    | '/reset-password'
    | '/accounting'
    | '/billing'
    | '/branches'
    | '/budgets'
    | '/cash-closing'
    | '/crm'
    | '/cs'
    | '/customers'
    | '/dashboard'
    | '/driver'
    | '/finance'
    | '/inventory'
    | '/ledger'
    | '/live-map'
    | '/manager'
    | '/ops'
    | '/receivables'
    | '/reports'
    | '/services'
    | '/settings'
    | '/system-health'
    | '/today'
    | '/join/$slug'
    | '/track/$token'
    | '/'
    | '/admin/billing'
    | '/admin/platform-fees'
    | '/branches/$id'
    | '/orders/$id'
    | '/orders/new'
    | '/pickups/new'
    | '/staff/$id'
    | '/staff/ironing-payroll'
    | '/staff/leaves'
    | '/staff/new'
    | '/staff/requests'
    | '/staff/salaries'
    | '/staff/schedule'
    | '/staff/users'
    | '/stations/cleaning'
    | '/stations/delivery'
    | '/stations/ironing'
    | '/stations/packing'
    | '/stations/qc'
    | '/stations/reception'
    | '/orders'
    | '/pickups'
    | '/staff'
    | '/admin/tenants/$id'
    | '/admin/tenants'
    | '/admin/users'
  id:
    | '__root__'
    | '/$slug'
    | '/_app'
    | '/customer-portal'
    | '/login'
    | '/reset-password'
    | '/_app/accounting'
    | '/_app/billing'
    | '/_app/branches'
    | '/_app/budgets'
    | '/_app/cash-closing'
    | '/_app/crm'
    | '/_app/cs'
    | '/_app/customers'
    | '/_app/dashboard'
    | '/_app/driver'
    | '/_app/finance'
    | '/_app/inventory'
    | '/_app/ledger'
    | '/_app/live-map'
    | '/_app/manager'
    | '/_app/ops'
    | '/_app/receivables'
    | '/_app/reports'
    | '/_app/services'
    | '/_app/settings'
    | '/_app/system-health'
    | '/_app/today'
    | '/join/$slug'
    | '/track/$token'
    | '/_app/'
    | '/_app/admin/billing'
    | '/_app/admin/platform-fees'
    | '/_app/branches/$id'
    | '/_app/orders/$id'
    | '/_app/orders/new'
    | '/_app/pickups/new'
    | '/_app/staff/$id'
    | '/_app/staff/ironing-payroll'
    | '/_app/staff/leaves'
    | '/_app/staff/new'
    | '/_app/staff/requests'
    | '/_app/staff/salaries'
    | '/_app/staff/schedule'
    | '/_app/staff/users'
    | '/_app/stations/cleaning'
    | '/_app/stations/delivery'
    | '/_app/stations/ironing'
    | '/_app/stations/packing'
    | '/_app/stations/qc'
    | '/_app/stations/reception'
    | '/_app/orders/'
    | '/_app/pickups/'
    | '/_app/staff/'
    | '/_app/admin/tenants/$id'
    | '/_app/admin/tenants/'
    | '/_app/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SlugRoute: typeof SlugRoute
  AppRoute: typeof AppRouteWithChildren
  CustomerPortalRoute: typeof CustomerPortalRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  JoinSlugRoute: typeof JoinSlugRoute
  TrackTokenRoute: typeof TrackTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-portal': {
      id: '/customer-portal'
      path: '/customer-portal'
      fullPath: '/customer-portal'
      preLoaderRoute: typeof CustomerPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/track/$token': {
      id: '/track/$token'
      path: '/track/$token'
      fullPath: '/track/$token'
      preLoaderRoute: typeof TrackTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$slug': {
      id: '/join/$slug'
      path: '/join/$slug'
      fullPath: '/join/$slug'
      preLoaderRoute: typeof JoinSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/today': {
      id: '/_app/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AppTodayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system-health': {
      id: '/_app/system-health'
      path: '/system-health'
      fullPath: '/system-health'
      preLoaderRoute: typeof AppSystemHealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services': {
      id: '/_app/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AppServicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/receivables': {
      id: '/_app/receivables'
      path: '/receivables'
      fullPath: '/receivables'
      preLoaderRoute: typeof AppReceivablesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ops': {
      id: '/_app/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof AppOpsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manager': {
      id: '/_app/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof AppManagerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/live-map': {
      id: '/_app/live-map'
      path: '/live-map'
      fullPath: '/live-map'
      preLoaderRoute: typeof AppLiveMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ledger': {
      id: '/_app/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof AppLedgerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance': {
      id: '/_app/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/driver': {
      id: '/_app/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof AppDriverRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cs': {
      id: '/_app/cs'
      path: '/cs'
      fullPath: '/cs'
      preLoaderRoute: typeof AppCsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm': {
      id: '/_app/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cash-closing': {
      id: '/_app/cash-closing'
      path: '/cash-closing'
      fullPath: '/cash-closing'
      preLoaderRoute: typeof AppCashClosingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/budgets': {
      id: '/_app/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof AppBudgetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/branches': {
      id: '/_app/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof AppBranchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounting': {
      id: '/_app/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AppAccountingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff/': {
      id: '/_app/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof AppStaffIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pickups/': {
      id: '/_app/pickups/'
      path: '/pickups'
      fullPath: '/pickups/'
      preLoaderRoute: typeof AppPickupsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/': {
      id: '/_app/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AppOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stations/reception': {
      id: '/_app/stations/reception'
      path: '/stations/reception'
      fullPath: '/stations/reception'
      preLoaderRoute: typeof AppStationsReceptionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stations/qc': {
      id: '/_app/stations/qc'
      path: '/stations/qc'
      fullPath: '/stations/qc'
      preLoaderRoute: typeof AppStationsQcRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stations/packing': {
      id: '/_app/stations/packing'
      path: '/stations/packing'
      fullPath: '/stations/packing'
      preLoaderRoute: typeof AppStationsPackingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stations/ironing': {
      id: '/_app/stations/ironing'
      path: '/stations/ironing'
      fullPath: '/stations/ironing'
      preLoaderRoute: typeof AppStationsIroningRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stations/delivery': {
      id: '/_app/stations/delivery'
      path: '/stations/delivery'
      fullPath: '/stations/delivery'
      preLoaderRoute: typeof AppStationsDeliveryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stations/cleaning': {
      id: '/_app/stations/cleaning'
      path: '/stations/cleaning'
      fullPath: '/stations/cleaning'
      preLoaderRoute: typeof AppStationsCleaningRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff/users': {
      id: '/_app/staff/users'
      path: '/staff/users'
      fullPath: '/staff/users'
      preLoaderRoute: typeof AppStaffUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff/schedule': {
      id: '/_app/staff/schedule'
      path: '/staff/schedule'
      fullPath: '/staff/schedule'
      preLoaderRoute: typeof AppStaffScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff/salaries': {
      id: '/_app/staff/salaries'
      path: '/staff/salaries'
      fullPath: '/staff/salaries'
      preLoaderRoute: typeof AppStaffSalariesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff/requests': {
      id: '/_app/staff/requests'
      path: '/staff/requests'
      fullPath: '/staff/requests'
      preLoaderRoute: typeof AppStaffRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff/new': {
      id: '/_app/staff/new'
      path: '/staff/new'
      fullPath: '/staff/new'
      preLoaderRoute: typeof AppStaffNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff/leaves': {
      id: '/_app/staff/leaves'
      path: '/staff/leaves'
      fullPath: '/staff/leaves'
      preLoaderRoute: typeof AppStaffLeavesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff/ironing-payroll': {
      id: '/_app/staff/ironing-payroll'
      path: '/staff/ironing-payroll'
      fullPath: '/staff/ironing-payroll'
      preLoaderRoute: typeof AppStaffIroningPayrollRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff/$id': {
      id: '/_app/staff/$id'
      path: '/staff/$id'
      fullPath: '/staff/$id'
      preLoaderRoute: typeof AppStaffIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pickups/new': {
      id: '/_app/pickups/new'
      path: '/pickups/new'
      fullPath: '/pickups/new'
      preLoaderRoute: typeof AppPickupsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/new': {
      id: '/_app/orders/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof AppOrdersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/$id': {
      id: '/_app/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AppOrdersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/branches/$id': {
      id: '/_app/branches/$id'
      path: '/$id'
      fullPath: '/branches/$id'
      preLoaderRoute: typeof AppBranchesIdRouteImport
      parentRoute: typeof AppBranchesRoute
    }
    '/_app/admin/platform-fees': {
      id: '/_app/admin/platform-fees'
      path: '/admin/platform-fees'
      fullPath: '/admin/platform-fees'
      preLoaderRoute: typeof AppAdminPlatformFeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/billing': {
      id: '/_app/admin/billing'
      path: '/admin/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AppAdminBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users/': {
      id: '/_app/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AppAdminUsersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/tenants/': {
      id: '/_app/admin/tenants/'
      path: '/admin/tenants'
      fullPath: '/admin/tenants/'
      preLoaderRoute: typeof AppAdminTenantsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/tenants/$id': {
      id: '/_app/admin/tenants/$id'
      path: '/admin/tenants/$id'
      fullPath: '/admin/tenants/$id'
      preLoaderRoute: typeof AppAdminTenantsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppBranchesRouteChildren {
  AppBranchesIdRoute: typeof AppBranchesIdRoute
}

const AppBranchesRouteChildren: AppBranchesRouteChildren = {
  AppBranchesIdRoute: AppBranchesIdRoute,
}

const AppBranchesRouteWithChildren = AppBranchesRoute._addFileChildren(
  AppBranchesRouteChildren,
)

interface AppRouteChildren {
  AppAccountingRoute: typeof AppAccountingRoute
  AppBillingRoute: typeof AppBillingRoute
  AppBranchesRoute: typeof AppBranchesRouteWithChildren
  AppBudgetsRoute: typeof AppBudgetsRoute
  AppCashClosingRoute: typeof AppCashClosingRoute
  AppCrmRoute: typeof AppCrmRoute
  AppCsRoute: typeof AppCsRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDriverRoute: typeof AppDriverRoute
  AppFinanceRoute: typeof AppFinanceRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppLedgerRoute: typeof AppLedgerRoute
  AppLiveMapRoute: typeof AppLiveMapRoute
  AppManagerRoute: typeof AppManagerRoute
  AppOpsRoute: typeof AppOpsRoute
  AppReceivablesRoute: typeof AppReceivablesRoute
  AppReportsRoute: typeof AppReportsRoute
  AppServicesRoute: typeof AppServicesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSystemHealthRoute: typeof AppSystemHealthRoute
  AppTodayRoute: typeof AppTodayRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminBillingRoute: typeof AppAdminBillingRoute
  AppAdminPlatformFeesRoute: typeof AppAdminPlatformFeesRoute
  AppOrdersIdRoute: typeof AppOrdersIdRoute
  AppOrdersNewRoute: typeof AppOrdersNewRoute
  AppPickupsNewRoute: typeof AppPickupsNewRoute
  AppStaffIdRoute: typeof AppStaffIdRoute
  AppStaffIroningPayrollRoute: typeof AppStaffIroningPayrollRoute
  AppStaffLeavesRoute: typeof AppStaffLeavesRoute
  AppStaffNewRoute: typeof AppStaffNewRoute
  AppStaffRequestsRoute: typeof AppStaffRequestsRoute
  AppStaffSalariesRoute: typeof AppStaffSalariesRoute
  AppStaffScheduleRoute: typeof AppStaffScheduleRoute
  AppStaffUsersRoute: typeof AppStaffUsersRoute
  AppStationsCleaningRoute: typeof AppStationsCleaningRoute
  AppStationsDeliveryRoute: typeof AppStationsDeliveryRoute
  AppStationsIroningRoute: typeof AppStationsIroningRoute
  AppStationsPackingRoute: typeof AppStationsPackingRoute
  AppStationsQcRoute: typeof AppStationsQcRoute
  AppStationsReceptionRoute: typeof AppStationsReceptionRoute
  AppOrdersIndexRoute: typeof AppOrdersIndexRoute
  AppPickupsIndexRoute: typeof AppPickupsIndexRoute
  AppStaffIndexRoute: typeof AppStaffIndexRoute
  AppAdminTenantsIdRoute: typeof AppAdminTenantsIdRoute
  AppAdminTenantsIndexRoute: typeof AppAdminTenantsIndexRoute
  AppAdminUsersIndexRoute: typeof AppAdminUsersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountingRoute: AppAccountingRoute,
  AppBillingRoute: AppBillingRoute,
  AppBranchesRoute: AppBranchesRouteWithChildren,
  AppBudgetsRoute: AppBudgetsRoute,
  AppCashClosingRoute: AppCashClosingRoute,
  AppCrmRoute: AppCrmRoute,
  AppCsRoute: AppCsRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDriverRoute: AppDriverRoute,
  AppFinanceRoute: AppFinanceRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppLedgerRoute: AppLedgerRoute,
  AppLiveMapRoute: AppLiveMapRoute,
  AppManagerRoute: AppManagerRoute,
  AppOpsRoute: AppOpsRoute,
  AppReceivablesRoute: AppReceivablesRoute,
  AppReportsRoute: AppReportsRoute,
  AppServicesRoute: AppServicesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSystemHealthRoute: AppSystemHealthRoute,
  AppTodayRoute: AppTodayRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminBillingRoute: AppAdminBillingRoute,
  AppAdminPlatformFeesRoute: AppAdminPlatformFeesRoute,
  AppOrdersIdRoute: AppOrdersIdRoute,
  AppOrdersNewRoute: AppOrdersNewRoute,
  AppPickupsNewRoute: AppPickupsNewRoute,
  AppStaffIdRoute: AppStaffIdRoute,
  AppStaffIroningPayrollRoute: AppStaffIroningPayrollRoute,
  AppStaffLeavesRoute: AppStaffLeavesRoute,
  AppStaffNewRoute: AppStaffNewRoute,
  AppStaffRequestsRoute: AppStaffRequestsRoute,
  AppStaffSalariesRoute: AppStaffSalariesRoute,
  AppStaffScheduleRoute: AppStaffScheduleRoute,
  AppStaffUsersRoute: AppStaffUsersRoute,
  AppStationsCleaningRoute: AppStationsCleaningRoute,
  AppStationsDeliveryRoute: AppStationsDeliveryRoute,
  AppStationsIroningRoute: AppStationsIroningRoute,
  AppStationsPackingRoute: AppStationsPackingRoute,
  AppStationsQcRoute: AppStationsQcRoute,
  AppStationsReceptionRoute: AppStationsReceptionRoute,
  AppOrdersIndexRoute: AppOrdersIndexRoute,
  AppPickupsIndexRoute: AppPickupsIndexRoute,
  AppStaffIndexRoute: AppStaffIndexRoute,
  AppAdminTenantsIdRoute: AppAdminTenantsIdRoute,
  AppAdminTenantsIndexRoute: AppAdminTenantsIndexRoute,
  AppAdminUsersIndexRoute: AppAdminUsersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SlugRoute: SlugRoute,
  AppRoute: AppRouteWithChildren,
  CustomerPortalRoute: CustomerPortalRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  JoinSlugRoute: JoinSlugRoute,
  TrackTokenRoute: TrackTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
