/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as CustomerPortalRouteImport } from './routes/customer-portal'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as TenantRouteImport } from './routes/$tenant'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackTokenRouteImport } from './routes/track.$token'
import { Route as JoinSlugRouteImport } from './routes/join.$slug'
import { Route as TenantWorkOrdersRouteImport } from './routes/$tenant/work-orders'
import { Route as TenantTodayRouteImport } from './routes/$tenant/today'
import { Route as TenantSystemHealthRouteImport } from './routes/$tenant/system-health'
import { Route as TenantSubscriptionsRouteImport } from './routes/$tenant/subscriptions'
import { Route as TenantSettingsRouteImport } from './routes/$tenant/settings'
import { Route as TenantServicesRouteImport } from './routes/$tenant/services'
import { Route as TenantSearchRouteImport } from './routes/$tenant/search'
import { Route as TenantReportsRouteImport } from './routes/$tenant/reports'
import { Route as TenantReceivablesRouteImport } from './routes/$tenant/receivables'
import { Route as TenantOpsRouteImport } from './routes/$tenant/ops'
import { Route as TenantOnboardingRouteImport } from './routes/$tenant/onboarding'
import { Route as TenantMarketplaceRouteImport } from './routes/$tenant/marketplace'
import { Route as TenantMarketingRouteImport } from './routes/$tenant/marketing'
import { Route as TenantManagerRouteImport } from './routes/$tenant/manager'
import { Route as TenantLiveMapRouteImport } from './routes/$tenant/live-map'
import { Route as TenantLegalRouteImport } from './routes/$tenant/legal'
import { Route as TenantLedgerRouteImport } from './routes/$tenant/ledger'
import { Route as TenantIssuesRouteImport } from './routes/$tenant/issues'
import { Route as TenantInventoryRouteImport } from './routes/$tenant/inventory'
import { Route as TenantHelpRouteImport } from './routes/$tenant/help'
import { Route as TenantFinanceRouteImport } from './routes/$tenant/finance'
import { Route as TenantExecutiveRouteImport } from './routes/$tenant/executive'
import { Route as TenantDriverRouteImport } from './routes/$tenant/driver'
import { Route as TenantDemoRouteImport } from './routes/$tenant/demo'
import { Route as TenantDashboardRouteImport } from './routes/$tenant/dashboard'
import { Route as TenantDailyOperationsRouteImport } from './routes/$tenant/daily-operations'
import { Route as TenantCustomersRouteImport } from './routes/$tenant/customers'
import { Route as TenantCustomerCareRouteImport } from './routes/$tenant/customer-care'
import { Route as TenantCsRouteImport } from './routes/$tenant/cs'
import { Route as TenantCrmRouteImport } from './routes/$tenant/crm'
import { Route as TenantCashClosingRouteImport } from './routes/$tenant/cash-closing'
import { Route as TenantBudgetsRouteImport } from './routes/$tenant/budgets'
import { Route as TenantBranchesRouteImport } from './routes/$tenant/branches'
import { Route as TenantBillingRouteImport } from './routes/$tenant/billing'
import { Route as TenantAccountingRouteImport } from './routes/$tenant/accounting'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin/index'
import { Route as TenantStaffIndexRouteImport } from './routes/$tenant/staff/index'
import { Route as TenantSettingsIndexRouteImport } from './routes/$tenant/settings/index'
import { Route as TenantPickupsIndexRouteImport } from './routes/$tenant/pickups/index'
import { Route as TenantOrdersIndexRouteImport } from './routes/$tenant/orders/index'
import { Route as AdminAdminWorkflowBuilderRouteImport } from './routes/_admin/admin/workflow-builder'
import { Route as AdminAdminTemplatesRouteImport } from './routes/_admin/admin/templates'
import { Route as AdminAdminTelemetryRouteImport } from './routes/_admin/admin/telemetry'
import { Route as AdminAdminReportBuilderRouteImport } from './routes/_admin/admin/report-builder'
import { Route as AdminAdminPlatformFeesRouteImport } from './routes/_admin/admin/platform-fees'
import { Route as AdminAdminPlatformBuilderRouteImport } from './routes/_admin/admin/platform-builder'
import { Route as AdminAdminMarketingPlanRouteImport } from './routes/_admin/admin/marketing-plan'
import { Route as AdminAdminLegalRouteImport } from './routes/_admin/admin/legal'
import { Route as AdminAdminInvestorRelationsRouteImport } from './routes/_admin/admin/investor-relations'
import { Route as AdminAdminInputBuilderRouteImport } from './routes/_admin/admin/input-builder'
import { Route as AdminAdminDemoLibraryRouteImport } from './routes/_admin/admin/demo-library'
import { Route as AdminAdminCustomerSuccessRouteImport } from './routes/_admin/admin/customer-success'
import { Route as AdminAdminBusinessPlanRouteImport } from './routes/_admin/admin/business-plan'
import { Route as AdminAdminBizDevRouteImport } from './routes/_admin/admin/biz-dev'
import { Route as AdminAdminBillingRouteImport } from './routes/_admin/admin/billing'
import { Route as TenantStationsSortingRouteImport } from './routes/$tenant/stations/sorting'
import { Route as TenantStationsReceptionRouteImport } from './routes/$tenant/stations/reception'
import { Route as TenantStationsQcRouteImport } from './routes/$tenant/stations/qc'
import { Route as TenantStationsPackingRouteImport } from './routes/$tenant/stations/packing'
import { Route as TenantStationsIroningRouteImport } from './routes/$tenant/stations/ironing'
import { Route as TenantStationsIntakeRouteImport } from './routes/$tenant/stations/intake'
import { Route as TenantStationsDryingAssemblyRouteImport } from './routes/$tenant/stations/drying-assembly'
import { Route as TenantStationsDeliveryRouteImport } from './routes/$tenant/stations/delivery'
import { Route as TenantStationsCsRouteImport } from './routes/$tenant/stations/cs'
import { Route as TenantStationsCleaningRouteImport } from './routes/$tenant/stations/cleaning'
import { Route as TenantStationsStageRouteImport } from './routes/$tenant/stations/$stage'
import { Route as TenantStaffUsersRouteImport } from './routes/$tenant/staff/users'
import { Route as TenantStaffScorecardRouteImport } from './routes/$tenant/staff/scorecard'
import { Route as TenantStaffScheduleRouteImport } from './routes/$tenant/staff/schedule'
import { Route as TenantStaffSalariesRouteImport } from './routes/$tenant/staff/salaries'
import { Route as TenantStaffRequestsRouteImport } from './routes/$tenant/staff/requests'
import { Route as TenantStaffNewRouteImport } from './routes/$tenant/staff/new'
import { Route as TenantStaffLeavesRouteImport } from './routes/$tenant/staff/leaves'
import { Route as TenantStaffIroningPayrollRouteImport } from './routes/$tenant/staff/ironing-payroll'
import { Route as TenantStaffFairnessRouteImport } from './routes/$tenant/staff/fairness'
import { Route as TenantStaffAttendanceRouteImport } from './routes/$tenant/staff/attendance'
import { Route as TenantStaffIdRouteImport } from './routes/$tenant/staff/$id'
import { Route as TenantSettingsWorkflowRouteImport } from './routes/$tenant/settings/workflow'
import { Route as TenantSettingsRolesRouteImport } from './routes/$tenant/settings/roles'
import { Route as TenantReportsBuilderRouteImport } from './routes/$tenant/reports/builder'
import { Route as TenantPickupsNewRouteImport } from './routes/$tenant/pickups/new'
import { Route as TenantOrdersNewRouteImport } from './routes/$tenant/orders/new'
import { Route as TenantOrdersIdRouteImport } from './routes/$tenant/orders/$id'
import { Route as TenantBranchesIdRouteImport } from './routes/$tenant/branches/$id'
import { Route as AdminAdminUsersIndexRouteImport } from './routes/_admin/admin/users/index'
import { Route as AdminAdminTenantsIndexRouteImport } from './routes/_admin/admin/tenants/index'
import { Route as TenantSettingsWorkflowIndexRouteImport } from './routes/$tenant/settings/workflow/index'
import { Route as AdminAdminTenantsIdRouteImport } from './routes/_admin/admin/tenants/$id'
import { Route as TenantSettingsWorkflowStageIdFieldsRouteImport } from './routes/$tenant/settings/workflow/$stageId/fields'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerPortalRoute = CustomerPortalRouteImport.update({
  id: '/customer-portal',
  path: '/customer-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantRoute = TenantRouteImport.update({
  id: '/$tenant',
  path: '/$tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackTokenRoute = TrackTokenRouteImport.update({
  id: '/track/$token',
  path: '/track/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinSlugRoute = JoinSlugRouteImport.update({
  id: '/join/$slug',
  path: '/join/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantWorkOrdersRoute = TenantWorkOrdersRouteImport.update({
  id: '/work-orders',
  path: '/work-orders',
  getParentRoute: () => TenantRoute,
} as any)
const TenantTodayRoute = TenantTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => TenantRoute,
} as any)
const TenantSystemHealthRoute = TenantSystemHealthRouteImport.update({
  id: '/system-health',
  path: '/system-health',
  getParentRoute: () => TenantRoute,
} as any)
const TenantSubscriptionsRoute = TenantSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => TenantRoute,
} as any)
const TenantSettingsRoute = TenantSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TenantRoute,
} as any)
const TenantServicesRoute = TenantServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => TenantRoute,
} as any)
const TenantSearchRoute = TenantSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => TenantRoute,
} as any)
const TenantReportsRoute = TenantReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => TenantRoute,
} as any)
const TenantReceivablesRoute = TenantReceivablesRouteImport.update({
  id: '/receivables',
  path: '/receivables',
  getParentRoute: () => TenantRoute,
} as any)
const TenantOpsRoute = TenantOpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => TenantRoute,
} as any)
const TenantOnboardingRoute = TenantOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => TenantRoute,
} as any)
const TenantMarketplaceRoute = TenantMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => TenantRoute,
} as any)
const TenantMarketingRoute = TenantMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => TenantRoute,
} as any)
const TenantManagerRoute = TenantManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => TenantRoute,
} as any)
const TenantLiveMapRoute = TenantLiveMapRouteImport.update({
  id: '/live-map',
  path: '/live-map',
  getParentRoute: () => TenantRoute,
} as any)
const TenantLegalRoute = TenantLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => TenantRoute,
} as any)
const TenantLedgerRoute = TenantLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => TenantRoute,
} as any)
const TenantIssuesRoute = TenantIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => TenantRoute,
} as any)
const TenantInventoryRoute = TenantInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => TenantRoute,
} as any)
const TenantHelpRoute = TenantHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => TenantRoute,
} as any)
const TenantFinanceRoute = TenantFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => TenantRoute,
} as any)
const TenantExecutiveRoute = TenantExecutiveRouteImport.update({
  id: '/executive',
  path: '/executive',
  getParentRoute: () => TenantRoute,
} as any)
const TenantDriverRoute = TenantDriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => TenantRoute,
} as any)
const TenantDemoRoute = TenantDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => TenantRoute,
} as any)
const TenantDashboardRoute = TenantDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => TenantRoute,
} as any)
const TenantDailyOperationsRoute = TenantDailyOperationsRouteImport.update({
  id: '/daily-operations',
  path: '/daily-operations',
  getParentRoute: () => TenantRoute,
} as any)
const TenantCustomersRoute = TenantCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => TenantRoute,
} as any)
const TenantCustomerCareRoute = TenantCustomerCareRouteImport.update({
  id: '/customer-care',
  path: '/customer-care',
  getParentRoute: () => TenantRoute,
} as any)
const TenantCsRoute = TenantCsRouteImport.update({
  id: '/cs',
  path: '/cs',
  getParentRoute: () => TenantRoute,
} as any)
const TenantCrmRoute = TenantCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => TenantRoute,
} as any)
const TenantCashClosingRoute = TenantCashClosingRouteImport.update({
  id: '/cash-closing',
  path: '/cash-closing',
  getParentRoute: () => TenantRoute,
} as any)
const TenantBudgetsRoute = TenantBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => TenantRoute,
} as any)
const TenantBranchesRoute = TenantBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => TenantRoute,
} as any)
const TenantBillingRoute = TenantBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => TenantRoute,
} as any)
const TenantAccountingRoute = TenantAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => TenantRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const TenantStaffIndexRoute = TenantStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => TenantRoute,
} as any)
const TenantSettingsIndexRoute = TenantSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantSettingsRoute,
} as any)
const TenantPickupsIndexRoute = TenantPickupsIndexRouteImport.update({
  id: '/pickups/',
  path: '/pickups/',
  getParentRoute: () => TenantRoute,
} as any)
const TenantOrdersIndexRoute = TenantOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => TenantRoute,
} as any)
const AdminAdminWorkflowBuilderRoute =
  AdminAdminWorkflowBuilderRouteImport.update({
    id: '/admin/workflow-builder',
    path: '/admin/workflow-builder',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminTemplatesRoute = AdminAdminTemplatesRouteImport.update({
  id: '/admin/templates',
  path: '/admin/templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminTelemetryRoute = AdminAdminTelemetryRouteImport.update({
  id: '/admin/telemetry',
  path: '/admin/telemetry',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminReportBuilderRoute = AdminAdminReportBuilderRouteImport.update({
  id: '/admin/report-builder',
  path: '/admin/report-builder',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminPlatformFeesRoute = AdminAdminPlatformFeesRouteImport.update({
  id: '/admin/platform-fees',
  path: '/admin/platform-fees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminPlatformBuilderRoute =
  AdminAdminPlatformBuilderRouteImport.update({
    id: '/admin/platform-builder',
    path: '/admin/platform-builder',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminMarketingPlanRoute = AdminAdminMarketingPlanRouteImport.update({
  id: '/admin/marketing-plan',
  path: '/admin/marketing-plan',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminLegalRoute = AdminAdminLegalRouteImport.update({
  id: '/admin/legal',
  path: '/admin/legal',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminInvestorRelationsRoute =
  AdminAdminInvestorRelationsRouteImport.update({
    id: '/admin/investor-relations',
    path: '/admin/investor-relations',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminInputBuilderRoute = AdminAdminInputBuilderRouteImport.update({
  id: '/admin/input-builder',
  path: '/admin/input-builder',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminDemoLibraryRoute = AdminAdminDemoLibraryRouteImport.update({
  id: '/admin/demo-library',
  path: '/admin/demo-library',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminCustomerSuccessRoute =
  AdminAdminCustomerSuccessRouteImport.update({
    id: '/admin/customer-success',
    path: '/admin/customer-success',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminBusinessPlanRoute = AdminAdminBusinessPlanRouteImport.update({
  id: '/admin/business-plan',
  path: '/admin/business-plan',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminBizDevRoute = AdminAdminBizDevRouteImport.update({
  id: '/admin/biz-dev',
  path: '/admin/biz-dev',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminBillingRoute = AdminAdminBillingRouteImport.update({
  id: '/admin/billing',
  path: '/admin/billing',
  getParentRoute: () => AdminRoute,
} as any)
const TenantStationsSortingRoute = TenantStationsSortingRouteImport.update({
  id: '/stations/sorting',
  path: '/stations/sorting',
  getParentRoute: () => TenantRoute,
} as any)
const TenantStationsReceptionRoute = TenantStationsReceptionRouteImport.update({
  id: '/stations/reception',
  path: '/stations/reception',
  getParentRoute: () => TenantRoute,
} as any)
const TenantStationsQcRoute = TenantStationsQcRouteImport.update({
  id: '/stations/qc',
  path: '/stations/qc',
  getParentRoute: () => TenantRoute,
} as any)
const TenantStationsPackingRoute = TenantStationsPackingRouteImport.update({
  id: '/stations/packing',
  path: '/stations/packing',
  getParentRoute: () => TenantRoute,
} as any)
const TenantStationsIroningRoute = TenantStationsIroningRouteImport.update({
  id: '/stations/ironing',
  path: '/stations/ironing',
  getParentRoute: () => TenantRoute,
} as any)
const TenantStationsIntakeRoute = TenantStationsIntakeRouteImport.update({
  id: '/stations/intake',
  path: '/stations/intake',
  getParentRoute: () => TenantRoute,
} as any)
const TenantStationsDryingAssemblyRoute =
  TenantStationsDryingAssemblyRouteImport.update({
    id: '/stations/drying-assembly',
    path: '/stations/drying-assembly',
    getParentRoute: () => TenantRoute,
  } as any)
const TenantStationsDeliveryRoute = TenantStationsDeliveryRouteImport.update({
  id: '/stations/delivery',
  path: '/stations/delivery',
  getParentRoute: () => TenantRoute,
} as any)
const TenantStationsCsRoute = TenantStationsCsRouteImport.update({
  id: '/stations/cs',
  path: '/stations/cs',
  getParentRoute: () => TenantRoute,
} as any)
const TenantStationsCleaningRoute = TenantStationsCleaningRouteImport.update({
  id: '/stations/cleaning',
  path: '/stations/cleaning',
  getParentRoute: () => TenantRoute,
} as any)
const TenantStationsStageRoute = TenantStationsStageRouteImport.update({
  id: '/stations/$stage',
  path: '/stations/$stage',
  getParentRoute: () => TenantRoute,
} as any)
const TenantStaffUsersRoute = TenantStaffUsersRouteImport.update({
  id: '/staff/users',
  path: '/staff/users',
  getParentRoute: () => TenantRoute,
} as any)
const TenantStaffScorecardRoute = TenantStaffScorecardRouteImport.update({
  id: '/staff/scorecard',
  path: '/staff/scorecard',
  getParentRoute: () => TenantRoute,
} as any)
const TenantStaffScheduleRoute = TenantStaffScheduleRouteImport.update({
  id: '/staff/schedule',
  path: '/staff/schedule',
  getParentRoute: () => TenantRoute,
} as any)
const TenantStaffSalariesRoute = TenantStaffSalariesRouteImport.update({
  id: '/staff/salaries',
  path: '/staff/salaries',
  getParentRoute: () => TenantRoute,
} as any)
const TenantStaffRequestsRoute = TenantStaffRequestsRouteImport.update({
  id: '/staff/requests',
  path: '/staff/requests',
  getParentRoute: () => TenantRoute,
} as any)
const TenantStaffNewRoute = TenantStaffNewRouteImport.update({
  id: '/staff/new',
  path: '/staff/new',
  getParentRoute: () => TenantRoute,
} as any)
const TenantStaffLeavesRoute = TenantStaffLeavesRouteImport.update({
  id: '/staff/leaves',
  path: '/staff/leaves',
  getParentRoute: () => TenantRoute,
} as any)
const TenantStaffIroningPayrollRoute =
  TenantStaffIroningPayrollRouteImport.update({
    id: '/staff/ironing-payroll',
    path: '/staff/ironing-payroll',
    getParentRoute: () => TenantRoute,
  } as any)
const TenantStaffFairnessRoute = TenantStaffFairnessRouteImport.update({
  id: '/staff/fairness',
  path: '/staff/fairness',
  getParentRoute: () => TenantRoute,
} as any)
const TenantStaffAttendanceRoute = TenantStaffAttendanceRouteImport.update({
  id: '/staff/attendance',
  path: '/staff/attendance',
  getParentRoute: () => TenantRoute,
} as any)
const TenantStaffIdRoute = TenantStaffIdRouteImport.update({
  id: '/staff/$id',
  path: '/staff/$id',
  getParentRoute: () => TenantRoute,
} as any)
const TenantSettingsWorkflowRoute = TenantSettingsWorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => TenantSettingsRoute,
} as any)
const TenantSettingsRolesRoute = TenantSettingsRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => TenantSettingsRoute,
} as any)
const TenantReportsBuilderRoute = TenantReportsBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => TenantReportsRoute,
} as any)
const TenantPickupsNewRoute = TenantPickupsNewRouteImport.update({
  id: '/pickups/new',
  path: '/pickups/new',
  getParentRoute: () => TenantRoute,
} as any)
const TenantOrdersNewRoute = TenantOrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => TenantRoute,
} as any)
const TenantOrdersIdRoute = TenantOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => TenantRoute,
} as any)
const TenantBranchesIdRoute = TenantBranchesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TenantBranchesRoute,
} as any)
const AdminAdminUsersIndexRoute = AdminAdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminTenantsIndexRoute = AdminAdminTenantsIndexRouteImport.update({
  id: '/admin/tenants/',
  path: '/admin/tenants/',
  getParentRoute: () => AdminRoute,
} as any)
const TenantSettingsWorkflowIndexRoute =
  TenantSettingsWorkflowIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TenantSettingsWorkflowRoute,
  } as any)
const AdminAdminTenantsIdRoute = AdminAdminTenantsIdRouteImport.update({
  id: '/admin/tenants/$id',
  path: '/admin/tenants/$id',
  getParentRoute: () => AdminRoute,
} as any)
const TenantSettingsWorkflowStageIdFieldsRoute =
  TenantSettingsWorkflowStageIdFieldsRouteImport.update({
    id: '/$stageId/fields',
    path: '/$stageId/fields',
    getParentRoute: () => TenantSettingsWorkflowRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/$tenant': typeof TenantRouteWithChildren
  '/customer-portal': typeof CustomerPortalRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/$tenant/accounting': typeof TenantAccountingRoute
  '/$tenant/billing': typeof TenantBillingRoute
  '/$tenant/branches': typeof TenantBranchesRouteWithChildren
  '/$tenant/budgets': typeof TenantBudgetsRoute
  '/$tenant/cash-closing': typeof TenantCashClosingRoute
  '/$tenant/crm': typeof TenantCrmRoute
  '/$tenant/cs': typeof TenantCsRoute
  '/$tenant/customer-care': typeof TenantCustomerCareRoute
  '/$tenant/customers': typeof TenantCustomersRoute
  '/$tenant/daily-operations': typeof TenantDailyOperationsRoute
  '/$tenant/dashboard': typeof TenantDashboardRoute
  '/$tenant/demo': typeof TenantDemoRoute
  '/$tenant/driver': typeof TenantDriverRoute
  '/$tenant/executive': typeof TenantExecutiveRoute
  '/$tenant/finance': typeof TenantFinanceRoute
  '/$tenant/help': typeof TenantHelpRoute
  '/$tenant/inventory': typeof TenantInventoryRoute
  '/$tenant/issues': typeof TenantIssuesRoute
  '/$tenant/ledger': typeof TenantLedgerRoute
  '/$tenant/legal': typeof TenantLegalRoute
  '/$tenant/live-map': typeof TenantLiveMapRoute
  '/$tenant/manager': typeof TenantManagerRoute
  '/$tenant/marketing': typeof TenantMarketingRoute
  '/$tenant/marketplace': typeof TenantMarketplaceRoute
  '/$tenant/onboarding': typeof TenantOnboardingRoute
  '/$tenant/ops': typeof TenantOpsRoute
  '/$tenant/receivables': typeof TenantReceivablesRoute
  '/$tenant/reports': typeof TenantReportsRouteWithChildren
  '/$tenant/search': typeof TenantSearchRoute
  '/$tenant/services': typeof TenantServicesRoute
  '/$tenant/settings': typeof TenantSettingsRouteWithChildren
  '/$tenant/subscriptions': typeof TenantSubscriptionsRoute
  '/$tenant/system-health': typeof TenantSystemHealthRoute
  '/$tenant/today': typeof TenantTodayRoute
  '/$tenant/work-orders': typeof TenantWorkOrdersRoute
  '/join/$slug': typeof JoinSlugRoute
  '/track/$token': typeof TrackTokenRoute
  '/$tenant/branches/$id': typeof TenantBranchesIdRoute
  '/$tenant/orders/$id': typeof TenantOrdersIdRoute
  '/$tenant/orders/new': typeof TenantOrdersNewRoute
  '/$tenant/pickups/new': typeof TenantPickupsNewRoute
  '/$tenant/reports/builder': typeof TenantReportsBuilderRoute
  '/$tenant/settings/roles': typeof TenantSettingsRolesRoute
  '/$tenant/settings/workflow': typeof TenantSettingsWorkflowRouteWithChildren
  '/$tenant/staff/$id': typeof TenantStaffIdRoute
  '/$tenant/staff/attendance': typeof TenantStaffAttendanceRoute
  '/$tenant/staff/fairness': typeof TenantStaffFairnessRoute
  '/$tenant/staff/ironing-payroll': typeof TenantStaffIroningPayrollRoute
  '/$tenant/staff/leaves': typeof TenantStaffLeavesRoute
  '/$tenant/staff/new': typeof TenantStaffNewRoute
  '/$tenant/staff/requests': typeof TenantStaffRequestsRoute
  '/$tenant/staff/salaries': typeof TenantStaffSalariesRoute
  '/$tenant/staff/schedule': typeof TenantStaffScheduleRoute
  '/$tenant/staff/scorecard': typeof TenantStaffScorecardRoute
  '/$tenant/staff/users': typeof TenantStaffUsersRoute
  '/$tenant/stations/$stage': typeof TenantStationsStageRoute
  '/$tenant/stations/cleaning': typeof TenantStationsCleaningRoute
  '/$tenant/stations/cs': typeof TenantStationsCsRoute
  '/$tenant/stations/delivery': typeof TenantStationsDeliveryRoute
  '/$tenant/stations/drying-assembly': typeof TenantStationsDryingAssemblyRoute
  '/$tenant/stations/intake': typeof TenantStationsIntakeRoute
  '/$tenant/stations/ironing': typeof TenantStationsIroningRoute
  '/$tenant/stations/packing': typeof TenantStationsPackingRoute
  '/$tenant/stations/qc': typeof TenantStationsQcRoute
  '/$tenant/stations/reception': typeof TenantStationsReceptionRoute
  '/$tenant/stations/sorting': typeof TenantStationsSortingRoute
  '/admin/billing': typeof AdminAdminBillingRoute
  '/admin/biz-dev': typeof AdminAdminBizDevRoute
  '/admin/business-plan': typeof AdminAdminBusinessPlanRoute
  '/admin/customer-success': typeof AdminAdminCustomerSuccessRoute
  '/admin/demo-library': typeof AdminAdminDemoLibraryRoute
  '/admin/input-builder': typeof AdminAdminInputBuilderRoute
  '/admin/investor-relations': typeof AdminAdminInvestorRelationsRoute
  '/admin/legal': typeof AdminAdminLegalRoute
  '/admin/marketing-plan': typeof AdminAdminMarketingPlanRoute
  '/admin/platform-builder': typeof AdminAdminPlatformBuilderRoute
  '/admin/platform-fees': typeof AdminAdminPlatformFeesRoute
  '/admin/report-builder': typeof AdminAdminReportBuilderRoute
  '/admin/telemetry': typeof AdminAdminTelemetryRoute
  '/admin/templates': typeof AdminAdminTemplatesRoute
  '/admin/workflow-builder': typeof AdminAdminWorkflowBuilderRoute
  '/$tenant/orders/': typeof TenantOrdersIndexRoute
  '/$tenant/pickups/': typeof TenantPickupsIndexRoute
  '/$tenant/settings/': typeof TenantSettingsIndexRoute
  '/$tenant/staff/': typeof TenantStaffIndexRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/admin/tenants/$id': typeof AdminAdminTenantsIdRoute
  '/$tenant/settings/workflow/': typeof TenantSettingsWorkflowIndexRoute
  '/admin/tenants/': typeof AdminAdminTenantsIndexRoute
  '/admin/users/': typeof AdminAdminUsersIndexRoute
  '/$tenant/settings/workflow/$stageId/fields': typeof TenantSettingsWorkflowStageIdFieldsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/$tenant': typeof TenantRouteWithChildren
  '/customer-portal': typeof CustomerPortalRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/$tenant/accounting': typeof TenantAccountingRoute
  '/$tenant/billing': typeof TenantBillingRoute
  '/$tenant/branches': typeof TenantBranchesRouteWithChildren
  '/$tenant/budgets': typeof TenantBudgetsRoute
  '/$tenant/cash-closing': typeof TenantCashClosingRoute
  '/$tenant/crm': typeof TenantCrmRoute
  '/$tenant/cs': typeof TenantCsRoute
  '/$tenant/customer-care': typeof TenantCustomerCareRoute
  '/$tenant/customers': typeof TenantCustomersRoute
  '/$tenant/daily-operations': typeof TenantDailyOperationsRoute
  '/$tenant/dashboard': typeof TenantDashboardRoute
  '/$tenant/demo': typeof TenantDemoRoute
  '/$tenant/driver': typeof TenantDriverRoute
  '/$tenant/executive': typeof TenantExecutiveRoute
  '/$tenant/finance': typeof TenantFinanceRoute
  '/$tenant/help': typeof TenantHelpRoute
  '/$tenant/inventory': typeof TenantInventoryRoute
  '/$tenant/issues': typeof TenantIssuesRoute
  '/$tenant/ledger': typeof TenantLedgerRoute
  '/$tenant/legal': typeof TenantLegalRoute
  '/$tenant/live-map': typeof TenantLiveMapRoute
  '/$tenant/manager': typeof TenantManagerRoute
  '/$tenant/marketing': typeof TenantMarketingRoute
  '/$tenant/marketplace': typeof TenantMarketplaceRoute
  '/$tenant/onboarding': typeof TenantOnboardingRoute
  '/$tenant/ops': typeof TenantOpsRoute
  '/$tenant/receivables': typeof TenantReceivablesRoute
  '/$tenant/reports': typeof TenantReportsRouteWithChildren
  '/$tenant/search': typeof TenantSearchRoute
  '/$tenant/services': typeof TenantServicesRoute
  '/$tenant/subscriptions': typeof TenantSubscriptionsRoute
  '/$tenant/system-health': typeof TenantSystemHealthRoute
  '/$tenant/today': typeof TenantTodayRoute
  '/$tenant/work-orders': typeof TenantWorkOrdersRoute
  '/join/$slug': typeof JoinSlugRoute
  '/track/$token': typeof TrackTokenRoute
  '/$tenant/branches/$id': typeof TenantBranchesIdRoute
  '/$tenant/orders/$id': typeof TenantOrdersIdRoute
  '/$tenant/orders/new': typeof TenantOrdersNewRoute
  '/$tenant/pickups/new': typeof TenantPickupsNewRoute
  '/$tenant/reports/builder': typeof TenantReportsBuilderRoute
  '/$tenant/settings/roles': typeof TenantSettingsRolesRoute
  '/$tenant/staff/$id': typeof TenantStaffIdRoute
  '/$tenant/staff/attendance': typeof TenantStaffAttendanceRoute
  '/$tenant/staff/fairness': typeof TenantStaffFairnessRoute
  '/$tenant/staff/ironing-payroll': typeof TenantStaffIroningPayrollRoute
  '/$tenant/staff/leaves': typeof TenantStaffLeavesRoute
  '/$tenant/staff/new': typeof TenantStaffNewRoute
  '/$tenant/staff/requests': typeof TenantStaffRequestsRoute
  '/$tenant/staff/salaries': typeof TenantStaffSalariesRoute
  '/$tenant/staff/schedule': typeof TenantStaffScheduleRoute
  '/$tenant/staff/scorecard': typeof TenantStaffScorecardRoute
  '/$tenant/staff/users': typeof TenantStaffUsersRoute
  '/$tenant/stations/$stage': typeof TenantStationsStageRoute
  '/$tenant/stations/cleaning': typeof TenantStationsCleaningRoute
  '/$tenant/stations/cs': typeof TenantStationsCsRoute
  '/$tenant/stations/delivery': typeof TenantStationsDeliveryRoute
  '/$tenant/stations/drying-assembly': typeof TenantStationsDryingAssemblyRoute
  '/$tenant/stations/intake': typeof TenantStationsIntakeRoute
  '/$tenant/stations/ironing': typeof TenantStationsIroningRoute
  '/$tenant/stations/packing': typeof TenantStationsPackingRoute
  '/$tenant/stations/qc': typeof TenantStationsQcRoute
  '/$tenant/stations/reception': typeof TenantStationsReceptionRoute
  '/$tenant/stations/sorting': typeof TenantStationsSortingRoute
  '/admin/billing': typeof AdminAdminBillingRoute
  '/admin/biz-dev': typeof AdminAdminBizDevRoute
  '/admin/business-plan': typeof AdminAdminBusinessPlanRoute
  '/admin/customer-success': typeof AdminAdminCustomerSuccessRoute
  '/admin/demo-library': typeof AdminAdminDemoLibraryRoute
  '/admin/input-builder': typeof AdminAdminInputBuilderRoute
  '/admin/investor-relations': typeof AdminAdminInvestorRelationsRoute
  '/admin/legal': typeof AdminAdminLegalRoute
  '/admin/marketing-plan': typeof AdminAdminMarketingPlanRoute
  '/admin/platform-builder': typeof AdminAdminPlatformBuilderRoute
  '/admin/platform-fees': typeof AdminAdminPlatformFeesRoute
  '/admin/report-builder': typeof AdminAdminReportBuilderRoute
  '/admin/telemetry': typeof AdminAdminTelemetryRoute
  '/admin/templates': typeof AdminAdminTemplatesRoute
  '/admin/workflow-builder': typeof AdminAdminWorkflowBuilderRoute
  '/$tenant/orders': typeof TenantOrdersIndexRoute
  '/$tenant/pickups': typeof TenantPickupsIndexRoute
  '/$tenant/settings': typeof TenantSettingsIndexRoute
  '/$tenant/staff': typeof TenantStaffIndexRoute
  '/admin': typeof AdminAdminIndexRoute
  '/admin/tenants/$id': typeof AdminAdminTenantsIdRoute
  '/$tenant/settings/workflow': typeof TenantSettingsWorkflowIndexRoute
  '/admin/tenants': typeof AdminAdminTenantsIndexRoute
  '/admin/users': typeof AdminAdminUsersIndexRoute
  '/$tenant/settings/workflow/$stageId/fields': typeof TenantSettingsWorkflowStageIdFieldsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/$tenant': typeof TenantRouteWithChildren
  '/_admin': typeof AdminRouteWithChildren
  '/customer-portal': typeof CustomerPortalRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/$tenant/accounting': typeof TenantAccountingRoute
  '/$tenant/billing': typeof TenantBillingRoute
  '/$tenant/branches': typeof TenantBranchesRouteWithChildren
  '/$tenant/budgets': typeof TenantBudgetsRoute
  '/$tenant/cash-closing': typeof TenantCashClosingRoute
  '/$tenant/crm': typeof TenantCrmRoute
  '/$tenant/cs': typeof TenantCsRoute
  '/$tenant/customer-care': typeof TenantCustomerCareRoute
  '/$tenant/customers': typeof TenantCustomersRoute
  '/$tenant/daily-operations': typeof TenantDailyOperationsRoute
  '/$tenant/dashboard': typeof TenantDashboardRoute
  '/$tenant/demo': typeof TenantDemoRoute
  '/$tenant/driver': typeof TenantDriverRoute
  '/$tenant/executive': typeof TenantExecutiveRoute
  '/$tenant/finance': typeof TenantFinanceRoute
  '/$tenant/help': typeof TenantHelpRoute
  '/$tenant/inventory': typeof TenantInventoryRoute
  '/$tenant/issues': typeof TenantIssuesRoute
  '/$tenant/ledger': typeof TenantLedgerRoute
  '/$tenant/legal': typeof TenantLegalRoute
  '/$tenant/live-map': typeof TenantLiveMapRoute
  '/$tenant/manager': typeof TenantManagerRoute
  '/$tenant/marketing': typeof TenantMarketingRoute
  '/$tenant/marketplace': typeof TenantMarketplaceRoute
  '/$tenant/onboarding': typeof TenantOnboardingRoute
  '/$tenant/ops': typeof TenantOpsRoute
  '/$tenant/receivables': typeof TenantReceivablesRoute
  '/$tenant/reports': typeof TenantReportsRouteWithChildren
  '/$tenant/search': typeof TenantSearchRoute
  '/$tenant/services': typeof TenantServicesRoute
  '/$tenant/settings': typeof TenantSettingsRouteWithChildren
  '/$tenant/subscriptions': typeof TenantSubscriptionsRoute
  '/$tenant/system-health': typeof TenantSystemHealthRoute
  '/$tenant/today': typeof TenantTodayRoute
  '/$tenant/work-orders': typeof TenantWorkOrdersRoute
  '/join/$slug': typeof JoinSlugRoute
  '/track/$token': typeof TrackTokenRoute
  '/$tenant/branches/$id': typeof TenantBranchesIdRoute
  '/$tenant/orders/$id': typeof TenantOrdersIdRoute
  '/$tenant/orders/new': typeof TenantOrdersNewRoute
  '/$tenant/pickups/new': typeof TenantPickupsNewRoute
  '/$tenant/reports/builder': typeof TenantReportsBuilderRoute
  '/$tenant/settings/roles': typeof TenantSettingsRolesRoute
  '/$tenant/settings/workflow': typeof TenantSettingsWorkflowRouteWithChildren
  '/$tenant/staff/$id': typeof TenantStaffIdRoute
  '/$tenant/staff/attendance': typeof TenantStaffAttendanceRoute
  '/$tenant/staff/fairness': typeof TenantStaffFairnessRoute
  '/$tenant/staff/ironing-payroll': typeof TenantStaffIroningPayrollRoute
  '/$tenant/staff/leaves': typeof TenantStaffLeavesRoute
  '/$tenant/staff/new': typeof TenantStaffNewRoute
  '/$tenant/staff/requests': typeof TenantStaffRequestsRoute
  '/$tenant/staff/salaries': typeof TenantStaffSalariesRoute
  '/$tenant/staff/schedule': typeof TenantStaffScheduleRoute
  '/$tenant/staff/scorecard': typeof TenantStaffScorecardRoute
  '/$tenant/staff/users': typeof TenantStaffUsersRoute
  '/$tenant/stations/$stage': typeof TenantStationsStageRoute
  '/$tenant/stations/cleaning': typeof TenantStationsCleaningRoute
  '/$tenant/stations/cs': typeof TenantStationsCsRoute
  '/$tenant/stations/delivery': typeof TenantStationsDeliveryRoute
  '/$tenant/stations/drying-assembly': typeof TenantStationsDryingAssemblyRoute
  '/$tenant/stations/intake': typeof TenantStationsIntakeRoute
  '/$tenant/stations/ironing': typeof TenantStationsIroningRoute
  '/$tenant/stations/packing': typeof TenantStationsPackingRoute
  '/$tenant/stations/qc': typeof TenantStationsQcRoute
  '/$tenant/stations/reception': typeof TenantStationsReceptionRoute
  '/$tenant/stations/sorting': typeof TenantStationsSortingRoute
  '/_admin/admin/billing': typeof AdminAdminBillingRoute
  '/_admin/admin/biz-dev': typeof AdminAdminBizDevRoute
  '/_admin/admin/business-plan': typeof AdminAdminBusinessPlanRoute
  '/_admin/admin/customer-success': typeof AdminAdminCustomerSuccessRoute
  '/_admin/admin/demo-library': typeof AdminAdminDemoLibraryRoute
  '/_admin/admin/input-builder': typeof AdminAdminInputBuilderRoute
  '/_admin/admin/investor-relations': typeof AdminAdminInvestorRelationsRoute
  '/_admin/admin/legal': typeof AdminAdminLegalRoute
  '/_admin/admin/marketing-plan': typeof AdminAdminMarketingPlanRoute
  '/_admin/admin/platform-builder': typeof AdminAdminPlatformBuilderRoute
  '/_admin/admin/platform-fees': typeof AdminAdminPlatformFeesRoute
  '/_admin/admin/report-builder': typeof AdminAdminReportBuilderRoute
  '/_admin/admin/telemetry': typeof AdminAdminTelemetryRoute
  '/_admin/admin/templates': typeof AdminAdminTemplatesRoute
  '/_admin/admin/workflow-builder': typeof AdminAdminWorkflowBuilderRoute
  '/$tenant/orders/': typeof TenantOrdersIndexRoute
  '/$tenant/pickups/': typeof TenantPickupsIndexRoute
  '/$tenant/settings/': typeof TenantSettingsIndexRoute
  '/$tenant/staff/': typeof TenantStaffIndexRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_admin/admin/tenants/$id': typeof AdminAdminTenantsIdRoute
  '/$tenant/settings/workflow/': typeof TenantSettingsWorkflowIndexRoute
  '/_admin/admin/tenants/': typeof AdminAdminTenantsIndexRoute
  '/_admin/admin/users/': typeof AdminAdminUsersIndexRoute
  '/$tenant/settings/workflow/$stageId/fields': typeof TenantSettingsWorkflowStageIdFieldsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/$tenant'
    | '/customer-portal'
    | '/landing'
    | '/login'
    | '/marketplace'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/$tenant/accounting'
    | '/$tenant/billing'
    | '/$tenant/branches'
    | '/$tenant/budgets'
    | '/$tenant/cash-closing'
    | '/$tenant/crm'
    | '/$tenant/cs'
    | '/$tenant/customer-care'
    | '/$tenant/customers'
    | '/$tenant/daily-operations'
    | '/$tenant/dashboard'
    | '/$tenant/demo'
    | '/$tenant/driver'
    | '/$tenant/executive'
    | '/$tenant/finance'
    | '/$tenant/help'
    | '/$tenant/inventory'
    | '/$tenant/issues'
    | '/$tenant/ledger'
    | '/$tenant/legal'
    | '/$tenant/live-map'
    | '/$tenant/manager'
    | '/$tenant/marketing'
    | '/$tenant/marketplace'
    | '/$tenant/onboarding'
    | '/$tenant/ops'
    | '/$tenant/receivables'
    | '/$tenant/reports'
    | '/$tenant/search'
    | '/$tenant/services'
    | '/$tenant/settings'
    | '/$tenant/subscriptions'
    | '/$tenant/system-health'
    | '/$tenant/today'
    | '/$tenant/work-orders'
    | '/join/$slug'
    | '/track/$token'
    | '/$tenant/branches/$id'
    | '/$tenant/orders/$id'
    | '/$tenant/orders/new'
    | '/$tenant/pickups/new'
    | '/$tenant/reports/builder'
    | '/$tenant/settings/roles'
    | '/$tenant/settings/workflow'
    | '/$tenant/staff/$id'
    | '/$tenant/staff/attendance'
    | '/$tenant/staff/fairness'
    | '/$tenant/staff/ironing-payroll'
    | '/$tenant/staff/leaves'
    | '/$tenant/staff/new'
    | '/$tenant/staff/requests'
    | '/$tenant/staff/salaries'
    | '/$tenant/staff/schedule'
    | '/$tenant/staff/scorecard'
    | '/$tenant/staff/users'
    | '/$tenant/stations/$stage'
    | '/$tenant/stations/cleaning'
    | '/$tenant/stations/cs'
    | '/$tenant/stations/delivery'
    | '/$tenant/stations/drying-assembly'
    | '/$tenant/stations/intake'
    | '/$tenant/stations/ironing'
    | '/$tenant/stations/packing'
    | '/$tenant/stations/qc'
    | '/$tenant/stations/reception'
    | '/$tenant/stations/sorting'
    | '/admin/billing'
    | '/admin/biz-dev'
    | '/admin/business-plan'
    | '/admin/customer-success'
    | '/admin/demo-library'
    | '/admin/input-builder'
    | '/admin/investor-relations'
    | '/admin/legal'
    | '/admin/marketing-plan'
    | '/admin/platform-builder'
    | '/admin/platform-fees'
    | '/admin/report-builder'
    | '/admin/telemetry'
    | '/admin/templates'
    | '/admin/workflow-builder'
    | '/$tenant/orders/'
    | '/$tenant/pickups/'
    | '/$tenant/settings/'
    | '/$tenant/staff/'
    | '/admin/'
    | '/admin/tenants/$id'
    | '/$tenant/settings/workflow/'
    | '/admin/tenants/'
    | '/admin/users/'
    | '/$tenant/settings/workflow/$stageId/fields'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/$tenant'
    | '/customer-portal'
    | '/landing'
    | '/login'
    | '/marketplace'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/$tenant/accounting'
    | '/$tenant/billing'
    | '/$tenant/branches'
    | '/$tenant/budgets'
    | '/$tenant/cash-closing'
    | '/$tenant/crm'
    | '/$tenant/cs'
    | '/$tenant/customer-care'
    | '/$tenant/customers'
    | '/$tenant/daily-operations'
    | '/$tenant/dashboard'
    | '/$tenant/demo'
    | '/$tenant/driver'
    | '/$tenant/executive'
    | '/$tenant/finance'
    | '/$tenant/help'
    | '/$tenant/inventory'
    | '/$tenant/issues'
    | '/$tenant/ledger'
    | '/$tenant/legal'
    | '/$tenant/live-map'
    | '/$tenant/manager'
    | '/$tenant/marketing'
    | '/$tenant/marketplace'
    | '/$tenant/onboarding'
    | '/$tenant/ops'
    | '/$tenant/receivables'
    | '/$tenant/reports'
    | '/$tenant/search'
    | '/$tenant/services'
    | '/$tenant/subscriptions'
    | '/$tenant/system-health'
    | '/$tenant/today'
    | '/$tenant/work-orders'
    | '/join/$slug'
    | '/track/$token'
    | '/$tenant/branches/$id'
    | '/$tenant/orders/$id'
    | '/$tenant/orders/new'
    | '/$tenant/pickups/new'
    | '/$tenant/reports/builder'
    | '/$tenant/settings/roles'
    | '/$tenant/staff/$id'
    | '/$tenant/staff/attendance'
    | '/$tenant/staff/fairness'
    | '/$tenant/staff/ironing-payroll'
    | '/$tenant/staff/leaves'
    | '/$tenant/staff/new'
    | '/$tenant/staff/requests'
    | '/$tenant/staff/salaries'
    | '/$tenant/staff/schedule'
    | '/$tenant/staff/scorecard'
    | '/$tenant/staff/users'
    | '/$tenant/stations/$stage'
    | '/$tenant/stations/cleaning'
    | '/$tenant/stations/cs'
    | '/$tenant/stations/delivery'
    | '/$tenant/stations/drying-assembly'
    | '/$tenant/stations/intake'
    | '/$tenant/stations/ironing'
    | '/$tenant/stations/packing'
    | '/$tenant/stations/qc'
    | '/$tenant/stations/reception'
    | '/$tenant/stations/sorting'
    | '/admin/billing'
    | '/admin/biz-dev'
    | '/admin/business-plan'
    | '/admin/customer-success'
    | '/admin/demo-library'
    | '/admin/input-builder'
    | '/admin/investor-relations'
    | '/admin/legal'
    | '/admin/marketing-plan'
    | '/admin/platform-builder'
    | '/admin/platform-fees'
    | '/admin/report-builder'
    | '/admin/telemetry'
    | '/admin/templates'
    | '/admin/workflow-builder'
    | '/$tenant/orders'
    | '/$tenant/pickups'
    | '/$tenant/settings'
    | '/$tenant/staff'
    | '/admin'
    | '/admin/tenants/$id'
    | '/$tenant/settings/workflow'
    | '/admin/tenants'
    | '/admin/users'
    | '/$tenant/settings/workflow/$stageId/fields'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/$tenant'
    | '/_admin'
    | '/customer-portal'
    | '/landing'
    | '/login'
    | '/marketplace'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/$tenant/accounting'
    | '/$tenant/billing'
    | '/$tenant/branches'
    | '/$tenant/budgets'
    | '/$tenant/cash-closing'
    | '/$tenant/crm'
    | '/$tenant/cs'
    | '/$tenant/customer-care'
    | '/$tenant/customers'
    | '/$tenant/daily-operations'
    | '/$tenant/dashboard'
    | '/$tenant/demo'
    | '/$tenant/driver'
    | '/$tenant/executive'
    | '/$tenant/finance'
    | '/$tenant/help'
    | '/$tenant/inventory'
    | '/$tenant/issues'
    | '/$tenant/ledger'
    | '/$tenant/legal'
    | '/$tenant/live-map'
    | '/$tenant/manager'
    | '/$tenant/marketing'
    | '/$tenant/marketplace'
    | '/$tenant/onboarding'
    | '/$tenant/ops'
    | '/$tenant/receivables'
    | '/$tenant/reports'
    | '/$tenant/search'
    | '/$tenant/services'
    | '/$tenant/settings'
    | '/$tenant/subscriptions'
    | '/$tenant/system-health'
    | '/$tenant/today'
    | '/$tenant/work-orders'
    | '/join/$slug'
    | '/track/$token'
    | '/$tenant/branches/$id'
    | '/$tenant/orders/$id'
    | '/$tenant/orders/new'
    | '/$tenant/pickups/new'
    | '/$tenant/reports/builder'
    | '/$tenant/settings/roles'
    | '/$tenant/settings/workflow'
    | '/$tenant/staff/$id'
    | '/$tenant/staff/attendance'
    | '/$tenant/staff/fairness'
    | '/$tenant/staff/ironing-payroll'
    | '/$tenant/staff/leaves'
    | '/$tenant/staff/new'
    | '/$tenant/staff/requests'
    | '/$tenant/staff/salaries'
    | '/$tenant/staff/schedule'
    | '/$tenant/staff/scorecard'
    | '/$tenant/staff/users'
    | '/$tenant/stations/$stage'
    | '/$tenant/stations/cleaning'
    | '/$tenant/stations/cs'
    | '/$tenant/stations/delivery'
    | '/$tenant/stations/drying-assembly'
    | '/$tenant/stations/intake'
    | '/$tenant/stations/ironing'
    | '/$tenant/stations/packing'
    | '/$tenant/stations/qc'
    | '/$tenant/stations/reception'
    | '/$tenant/stations/sorting'
    | '/_admin/admin/billing'
    | '/_admin/admin/biz-dev'
    | '/_admin/admin/business-plan'
    | '/_admin/admin/customer-success'
    | '/_admin/admin/demo-library'
    | '/_admin/admin/input-builder'
    | '/_admin/admin/investor-relations'
    | '/_admin/admin/legal'
    | '/_admin/admin/marketing-plan'
    | '/_admin/admin/platform-builder'
    | '/_admin/admin/platform-fees'
    | '/_admin/admin/report-builder'
    | '/_admin/admin/telemetry'
    | '/_admin/admin/templates'
    | '/_admin/admin/workflow-builder'
    | '/$tenant/orders/'
    | '/$tenant/pickups/'
    | '/$tenant/settings/'
    | '/$tenant/staff/'
    | '/_admin/admin/'
    | '/_admin/admin/tenants/$id'
    | '/$tenant/settings/workflow/'
    | '/_admin/admin/tenants/'
    | '/_admin/admin/users/'
    | '/$tenant/settings/workflow/$stageId/fields'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  TenantRoute: typeof TenantRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  CustomerPortalRoute: typeof CustomerPortalRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  JoinSlugRoute: typeof JoinSlugRoute
  TrackTokenRoute: typeof TrackTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-portal': {
      id: '/customer-portal'
      path: '/customer-portal'
      fullPath: '/customer-portal'
      preLoaderRoute: typeof CustomerPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenant': {
      id: '/$tenant'
      path: '/$tenant'
      fullPath: '/$tenant'
      preLoaderRoute: typeof TenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$token': {
      id: '/track/$token'
      path: '/track/$token'
      fullPath: '/track/$token'
      preLoaderRoute: typeof TrackTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$slug': {
      id: '/join/$slug'
      path: '/join/$slug'
      fullPath: '/join/$slug'
      preLoaderRoute: typeof JoinSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenant/work-orders': {
      id: '/$tenant/work-orders'
      path: '/work-orders'
      fullPath: '/$tenant/work-orders'
      preLoaderRoute: typeof TenantWorkOrdersRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/today': {
      id: '/$tenant/today'
      path: '/today'
      fullPath: '/$tenant/today'
      preLoaderRoute: typeof TenantTodayRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/system-health': {
      id: '/$tenant/system-health'
      path: '/system-health'
      fullPath: '/$tenant/system-health'
      preLoaderRoute: typeof TenantSystemHealthRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/subscriptions': {
      id: '/$tenant/subscriptions'
      path: '/subscriptions'
      fullPath: '/$tenant/subscriptions'
      preLoaderRoute: typeof TenantSubscriptionsRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/settings': {
      id: '/$tenant/settings'
      path: '/settings'
      fullPath: '/$tenant/settings'
      preLoaderRoute: typeof TenantSettingsRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/services': {
      id: '/$tenant/services'
      path: '/services'
      fullPath: '/$tenant/services'
      preLoaderRoute: typeof TenantServicesRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/search': {
      id: '/$tenant/search'
      path: '/search'
      fullPath: '/$tenant/search'
      preLoaderRoute: typeof TenantSearchRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/reports': {
      id: '/$tenant/reports'
      path: '/reports'
      fullPath: '/$tenant/reports'
      preLoaderRoute: typeof TenantReportsRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/receivables': {
      id: '/$tenant/receivables'
      path: '/receivables'
      fullPath: '/$tenant/receivables'
      preLoaderRoute: typeof TenantReceivablesRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/ops': {
      id: '/$tenant/ops'
      path: '/ops'
      fullPath: '/$tenant/ops'
      preLoaderRoute: typeof TenantOpsRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/onboarding': {
      id: '/$tenant/onboarding'
      path: '/onboarding'
      fullPath: '/$tenant/onboarding'
      preLoaderRoute: typeof TenantOnboardingRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/marketplace': {
      id: '/$tenant/marketplace'
      path: '/marketplace'
      fullPath: '/$tenant/marketplace'
      preLoaderRoute: typeof TenantMarketplaceRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/marketing': {
      id: '/$tenant/marketing'
      path: '/marketing'
      fullPath: '/$tenant/marketing'
      preLoaderRoute: typeof TenantMarketingRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/manager': {
      id: '/$tenant/manager'
      path: '/manager'
      fullPath: '/$tenant/manager'
      preLoaderRoute: typeof TenantManagerRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/live-map': {
      id: '/$tenant/live-map'
      path: '/live-map'
      fullPath: '/$tenant/live-map'
      preLoaderRoute: typeof TenantLiveMapRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/legal': {
      id: '/$tenant/legal'
      path: '/legal'
      fullPath: '/$tenant/legal'
      preLoaderRoute: typeof TenantLegalRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/ledger': {
      id: '/$tenant/ledger'
      path: '/ledger'
      fullPath: '/$tenant/ledger'
      preLoaderRoute: typeof TenantLedgerRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/issues': {
      id: '/$tenant/issues'
      path: '/issues'
      fullPath: '/$tenant/issues'
      preLoaderRoute: typeof TenantIssuesRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/inventory': {
      id: '/$tenant/inventory'
      path: '/inventory'
      fullPath: '/$tenant/inventory'
      preLoaderRoute: typeof TenantInventoryRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/help': {
      id: '/$tenant/help'
      path: '/help'
      fullPath: '/$tenant/help'
      preLoaderRoute: typeof TenantHelpRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/finance': {
      id: '/$tenant/finance'
      path: '/finance'
      fullPath: '/$tenant/finance'
      preLoaderRoute: typeof TenantFinanceRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/executive': {
      id: '/$tenant/executive'
      path: '/executive'
      fullPath: '/$tenant/executive'
      preLoaderRoute: typeof TenantExecutiveRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/driver': {
      id: '/$tenant/driver'
      path: '/driver'
      fullPath: '/$tenant/driver'
      preLoaderRoute: typeof TenantDriverRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/demo': {
      id: '/$tenant/demo'
      path: '/demo'
      fullPath: '/$tenant/demo'
      preLoaderRoute: typeof TenantDemoRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/dashboard': {
      id: '/$tenant/dashboard'
      path: '/dashboard'
      fullPath: '/$tenant/dashboard'
      preLoaderRoute: typeof TenantDashboardRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/daily-operations': {
      id: '/$tenant/daily-operations'
      path: '/daily-operations'
      fullPath: '/$tenant/daily-operations'
      preLoaderRoute: typeof TenantDailyOperationsRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/customers': {
      id: '/$tenant/customers'
      path: '/customers'
      fullPath: '/$tenant/customers'
      preLoaderRoute: typeof TenantCustomersRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/customer-care': {
      id: '/$tenant/customer-care'
      path: '/customer-care'
      fullPath: '/$tenant/customer-care'
      preLoaderRoute: typeof TenantCustomerCareRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/cs': {
      id: '/$tenant/cs'
      path: '/cs'
      fullPath: '/$tenant/cs'
      preLoaderRoute: typeof TenantCsRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/crm': {
      id: '/$tenant/crm'
      path: '/crm'
      fullPath: '/$tenant/crm'
      preLoaderRoute: typeof TenantCrmRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/cash-closing': {
      id: '/$tenant/cash-closing'
      path: '/cash-closing'
      fullPath: '/$tenant/cash-closing'
      preLoaderRoute: typeof TenantCashClosingRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/budgets': {
      id: '/$tenant/budgets'
      path: '/budgets'
      fullPath: '/$tenant/budgets'
      preLoaderRoute: typeof TenantBudgetsRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/branches': {
      id: '/$tenant/branches'
      path: '/branches'
      fullPath: '/$tenant/branches'
      preLoaderRoute: typeof TenantBranchesRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/billing': {
      id: '/$tenant/billing'
      path: '/billing'
      fullPath: '/$tenant/billing'
      preLoaderRoute: typeof TenantBillingRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/accounting': {
      id: '/$tenant/accounting'
      path: '/accounting'
      fullPath: '/$tenant/accounting'
      preLoaderRoute: typeof TenantAccountingRouteImport
      parentRoute: typeof TenantRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$tenant/staff/': {
      id: '/$tenant/staff/'
      path: '/staff'
      fullPath: '/$tenant/staff/'
      preLoaderRoute: typeof TenantStaffIndexRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/settings/': {
      id: '/$tenant/settings/'
      path: '/'
      fullPath: '/$tenant/settings/'
      preLoaderRoute: typeof TenantSettingsIndexRouteImport
      parentRoute: typeof TenantSettingsRoute
    }
    '/$tenant/pickups/': {
      id: '/$tenant/pickups/'
      path: '/pickups'
      fullPath: '/$tenant/pickups/'
      preLoaderRoute: typeof TenantPickupsIndexRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/orders/': {
      id: '/$tenant/orders/'
      path: '/orders'
      fullPath: '/$tenant/orders/'
      preLoaderRoute: typeof TenantOrdersIndexRouteImport
      parentRoute: typeof TenantRoute
    }
    '/_admin/admin/workflow-builder': {
      id: '/_admin/admin/workflow-builder'
      path: '/admin/workflow-builder'
      fullPath: '/admin/workflow-builder'
      preLoaderRoute: typeof AdminAdminWorkflowBuilderRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/templates': {
      id: '/_admin/admin/templates'
      path: '/admin/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminAdminTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/telemetry': {
      id: '/_admin/admin/telemetry'
      path: '/admin/telemetry'
      fullPath: '/admin/telemetry'
      preLoaderRoute: typeof AdminAdminTelemetryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/report-builder': {
      id: '/_admin/admin/report-builder'
      path: '/admin/report-builder'
      fullPath: '/admin/report-builder'
      preLoaderRoute: typeof AdminAdminReportBuilderRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/platform-fees': {
      id: '/_admin/admin/platform-fees'
      path: '/admin/platform-fees'
      fullPath: '/admin/platform-fees'
      preLoaderRoute: typeof AdminAdminPlatformFeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/platform-builder': {
      id: '/_admin/admin/platform-builder'
      path: '/admin/platform-builder'
      fullPath: '/admin/platform-builder'
      preLoaderRoute: typeof AdminAdminPlatformBuilderRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/marketing-plan': {
      id: '/_admin/admin/marketing-plan'
      path: '/admin/marketing-plan'
      fullPath: '/admin/marketing-plan'
      preLoaderRoute: typeof AdminAdminMarketingPlanRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/legal': {
      id: '/_admin/admin/legal'
      path: '/admin/legal'
      fullPath: '/admin/legal'
      preLoaderRoute: typeof AdminAdminLegalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/investor-relations': {
      id: '/_admin/admin/investor-relations'
      path: '/admin/investor-relations'
      fullPath: '/admin/investor-relations'
      preLoaderRoute: typeof AdminAdminInvestorRelationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/input-builder': {
      id: '/_admin/admin/input-builder'
      path: '/admin/input-builder'
      fullPath: '/admin/input-builder'
      preLoaderRoute: typeof AdminAdminInputBuilderRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/demo-library': {
      id: '/_admin/admin/demo-library'
      path: '/admin/demo-library'
      fullPath: '/admin/demo-library'
      preLoaderRoute: typeof AdminAdminDemoLibraryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/customer-success': {
      id: '/_admin/admin/customer-success'
      path: '/admin/customer-success'
      fullPath: '/admin/customer-success'
      preLoaderRoute: typeof AdminAdminCustomerSuccessRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/business-plan': {
      id: '/_admin/admin/business-plan'
      path: '/admin/business-plan'
      fullPath: '/admin/business-plan'
      preLoaderRoute: typeof AdminAdminBusinessPlanRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/biz-dev': {
      id: '/_admin/admin/biz-dev'
      path: '/admin/biz-dev'
      fullPath: '/admin/biz-dev'
      preLoaderRoute: typeof AdminAdminBizDevRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/billing': {
      id: '/_admin/admin/billing'
      path: '/admin/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminAdminBillingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$tenant/stations/sorting': {
      id: '/$tenant/stations/sorting'
      path: '/stations/sorting'
      fullPath: '/$tenant/stations/sorting'
      preLoaderRoute: typeof TenantStationsSortingRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/stations/reception': {
      id: '/$tenant/stations/reception'
      path: '/stations/reception'
      fullPath: '/$tenant/stations/reception'
      preLoaderRoute: typeof TenantStationsReceptionRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/stations/qc': {
      id: '/$tenant/stations/qc'
      path: '/stations/qc'
      fullPath: '/$tenant/stations/qc'
      preLoaderRoute: typeof TenantStationsQcRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/stations/packing': {
      id: '/$tenant/stations/packing'
      path: '/stations/packing'
      fullPath: '/$tenant/stations/packing'
      preLoaderRoute: typeof TenantStationsPackingRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/stations/ironing': {
      id: '/$tenant/stations/ironing'
      path: '/stations/ironing'
      fullPath: '/$tenant/stations/ironing'
      preLoaderRoute: typeof TenantStationsIroningRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/stations/intake': {
      id: '/$tenant/stations/intake'
      path: '/stations/intake'
      fullPath: '/$tenant/stations/intake'
      preLoaderRoute: typeof TenantStationsIntakeRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/stations/drying-assembly': {
      id: '/$tenant/stations/drying-assembly'
      path: '/stations/drying-assembly'
      fullPath: '/$tenant/stations/drying-assembly'
      preLoaderRoute: typeof TenantStationsDryingAssemblyRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/stations/delivery': {
      id: '/$tenant/stations/delivery'
      path: '/stations/delivery'
      fullPath: '/$tenant/stations/delivery'
      preLoaderRoute: typeof TenantStationsDeliveryRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/stations/cs': {
      id: '/$tenant/stations/cs'
      path: '/stations/cs'
      fullPath: '/$tenant/stations/cs'
      preLoaderRoute: typeof TenantStationsCsRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/stations/cleaning': {
      id: '/$tenant/stations/cleaning'
      path: '/stations/cleaning'
      fullPath: '/$tenant/stations/cleaning'
      preLoaderRoute: typeof TenantStationsCleaningRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/stations/$stage': {
      id: '/$tenant/stations/$stage'
      path: '/stations/$stage'
      fullPath: '/$tenant/stations/$stage'
      preLoaderRoute: typeof TenantStationsStageRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/staff/users': {
      id: '/$tenant/staff/users'
      path: '/staff/users'
      fullPath: '/$tenant/staff/users'
      preLoaderRoute: typeof TenantStaffUsersRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/staff/scorecard': {
      id: '/$tenant/staff/scorecard'
      path: '/staff/scorecard'
      fullPath: '/$tenant/staff/scorecard'
      preLoaderRoute: typeof TenantStaffScorecardRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/staff/schedule': {
      id: '/$tenant/staff/schedule'
      path: '/staff/schedule'
      fullPath: '/$tenant/staff/schedule'
      preLoaderRoute: typeof TenantStaffScheduleRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/staff/salaries': {
      id: '/$tenant/staff/salaries'
      path: '/staff/salaries'
      fullPath: '/$tenant/staff/salaries'
      preLoaderRoute: typeof TenantStaffSalariesRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/staff/requests': {
      id: '/$tenant/staff/requests'
      path: '/staff/requests'
      fullPath: '/$tenant/staff/requests'
      preLoaderRoute: typeof TenantStaffRequestsRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/staff/new': {
      id: '/$tenant/staff/new'
      path: '/staff/new'
      fullPath: '/$tenant/staff/new'
      preLoaderRoute: typeof TenantStaffNewRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/staff/leaves': {
      id: '/$tenant/staff/leaves'
      path: '/staff/leaves'
      fullPath: '/$tenant/staff/leaves'
      preLoaderRoute: typeof TenantStaffLeavesRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/staff/ironing-payroll': {
      id: '/$tenant/staff/ironing-payroll'
      path: '/staff/ironing-payroll'
      fullPath: '/$tenant/staff/ironing-payroll'
      preLoaderRoute: typeof TenantStaffIroningPayrollRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/staff/fairness': {
      id: '/$tenant/staff/fairness'
      path: '/staff/fairness'
      fullPath: '/$tenant/staff/fairness'
      preLoaderRoute: typeof TenantStaffFairnessRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/staff/attendance': {
      id: '/$tenant/staff/attendance'
      path: '/staff/attendance'
      fullPath: '/$tenant/staff/attendance'
      preLoaderRoute: typeof TenantStaffAttendanceRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/staff/$id': {
      id: '/$tenant/staff/$id'
      path: '/staff/$id'
      fullPath: '/$tenant/staff/$id'
      preLoaderRoute: typeof TenantStaffIdRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/settings/workflow': {
      id: '/$tenant/settings/workflow'
      path: '/workflow'
      fullPath: '/$tenant/settings/workflow'
      preLoaderRoute: typeof TenantSettingsWorkflowRouteImport
      parentRoute: typeof TenantSettingsRoute
    }
    '/$tenant/settings/roles': {
      id: '/$tenant/settings/roles'
      path: '/roles'
      fullPath: '/$tenant/settings/roles'
      preLoaderRoute: typeof TenantSettingsRolesRouteImport
      parentRoute: typeof TenantSettingsRoute
    }
    '/$tenant/reports/builder': {
      id: '/$tenant/reports/builder'
      path: '/builder'
      fullPath: '/$tenant/reports/builder'
      preLoaderRoute: typeof TenantReportsBuilderRouteImport
      parentRoute: typeof TenantReportsRoute
    }
    '/$tenant/pickups/new': {
      id: '/$tenant/pickups/new'
      path: '/pickups/new'
      fullPath: '/$tenant/pickups/new'
      preLoaderRoute: typeof TenantPickupsNewRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/orders/new': {
      id: '/$tenant/orders/new'
      path: '/orders/new'
      fullPath: '/$tenant/orders/new'
      preLoaderRoute: typeof TenantOrdersNewRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/orders/$id': {
      id: '/$tenant/orders/$id'
      path: '/orders/$id'
      fullPath: '/$tenant/orders/$id'
      preLoaderRoute: typeof TenantOrdersIdRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/branches/$id': {
      id: '/$tenant/branches/$id'
      path: '/$id'
      fullPath: '/$tenant/branches/$id'
      preLoaderRoute: typeof TenantBranchesIdRouteImport
      parentRoute: typeof TenantBranchesRoute
    }
    '/_admin/admin/users/': {
      id: '/_admin/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminAdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/tenants/': {
      id: '/_admin/admin/tenants/'
      path: '/admin/tenants'
      fullPath: '/admin/tenants/'
      preLoaderRoute: typeof AdminAdminTenantsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$tenant/settings/workflow/': {
      id: '/$tenant/settings/workflow/'
      path: '/'
      fullPath: '/$tenant/settings/workflow/'
      preLoaderRoute: typeof TenantSettingsWorkflowIndexRouteImport
      parentRoute: typeof TenantSettingsWorkflowRoute
    }
    '/_admin/admin/tenants/$id': {
      id: '/_admin/admin/tenants/$id'
      path: '/admin/tenants/$id'
      fullPath: '/admin/tenants/$id'
      preLoaderRoute: typeof AdminAdminTenantsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$tenant/settings/workflow/$stageId/fields': {
      id: '/$tenant/settings/workflow/$stageId/fields'
      path: '/$stageId/fields'
      fullPath: '/$tenant/settings/workflow/$stageId/fields'
      preLoaderRoute: typeof TenantSettingsWorkflowStageIdFieldsRouteImport
      parentRoute: typeof TenantSettingsWorkflowRoute
    }
  }
}

interface TenantBranchesRouteChildren {
  TenantBranchesIdRoute: typeof TenantBranchesIdRoute
}

const TenantBranchesRouteChildren: TenantBranchesRouteChildren = {
  TenantBranchesIdRoute: TenantBranchesIdRoute,
}

const TenantBranchesRouteWithChildren = TenantBranchesRoute._addFileChildren(
  TenantBranchesRouteChildren,
)

interface TenantReportsRouteChildren {
  TenantReportsBuilderRoute: typeof TenantReportsBuilderRoute
}

const TenantReportsRouteChildren: TenantReportsRouteChildren = {
  TenantReportsBuilderRoute: TenantReportsBuilderRoute,
}

const TenantReportsRouteWithChildren = TenantReportsRoute._addFileChildren(
  TenantReportsRouteChildren,
)

interface TenantSettingsWorkflowRouteChildren {
  TenantSettingsWorkflowIndexRoute: typeof TenantSettingsWorkflowIndexRoute
  TenantSettingsWorkflowStageIdFieldsRoute: typeof TenantSettingsWorkflowStageIdFieldsRoute
}

const TenantSettingsWorkflowRouteChildren: TenantSettingsWorkflowRouteChildren =
  {
    TenantSettingsWorkflowIndexRoute: TenantSettingsWorkflowIndexRoute,
    TenantSettingsWorkflowStageIdFieldsRoute:
      TenantSettingsWorkflowStageIdFieldsRoute,
  }

const TenantSettingsWorkflowRouteWithChildren =
  TenantSettingsWorkflowRoute._addFileChildren(
    TenantSettingsWorkflowRouteChildren,
  )

interface TenantSettingsRouteChildren {
  TenantSettingsRolesRoute: typeof TenantSettingsRolesRoute
  TenantSettingsWorkflowRoute: typeof TenantSettingsWorkflowRouteWithChildren
  TenantSettingsIndexRoute: typeof TenantSettingsIndexRoute
}

const TenantSettingsRouteChildren: TenantSettingsRouteChildren = {
  TenantSettingsRolesRoute: TenantSettingsRolesRoute,
  TenantSettingsWorkflowRoute: TenantSettingsWorkflowRouteWithChildren,
  TenantSettingsIndexRoute: TenantSettingsIndexRoute,
}

const TenantSettingsRouteWithChildren = TenantSettingsRoute._addFileChildren(
  TenantSettingsRouteChildren,
)

interface TenantRouteChildren {
  TenantAccountingRoute: typeof TenantAccountingRoute
  TenantBillingRoute: typeof TenantBillingRoute
  TenantBranchesRoute: typeof TenantBranchesRouteWithChildren
  TenantBudgetsRoute: typeof TenantBudgetsRoute
  TenantCashClosingRoute: typeof TenantCashClosingRoute
  TenantCrmRoute: typeof TenantCrmRoute
  TenantCsRoute: typeof TenantCsRoute
  TenantCustomerCareRoute: typeof TenantCustomerCareRoute
  TenantCustomersRoute: typeof TenantCustomersRoute
  TenantDailyOperationsRoute: typeof TenantDailyOperationsRoute
  TenantDashboardRoute: typeof TenantDashboardRoute
  TenantDemoRoute: typeof TenantDemoRoute
  TenantDriverRoute: typeof TenantDriverRoute
  TenantExecutiveRoute: typeof TenantExecutiveRoute
  TenantFinanceRoute: typeof TenantFinanceRoute
  TenantHelpRoute: typeof TenantHelpRoute
  TenantInventoryRoute: typeof TenantInventoryRoute
  TenantIssuesRoute: typeof TenantIssuesRoute
  TenantLedgerRoute: typeof TenantLedgerRoute
  TenantLegalRoute: typeof TenantLegalRoute
  TenantLiveMapRoute: typeof TenantLiveMapRoute
  TenantManagerRoute: typeof TenantManagerRoute
  TenantMarketingRoute: typeof TenantMarketingRoute
  TenantMarketplaceRoute: typeof TenantMarketplaceRoute
  TenantOnboardingRoute: typeof TenantOnboardingRoute
  TenantOpsRoute: typeof TenantOpsRoute
  TenantReceivablesRoute: typeof TenantReceivablesRoute
  TenantReportsRoute: typeof TenantReportsRouteWithChildren
  TenantSearchRoute: typeof TenantSearchRoute
  TenantServicesRoute: typeof TenantServicesRoute
  TenantSettingsRoute: typeof TenantSettingsRouteWithChildren
  TenantSubscriptionsRoute: typeof TenantSubscriptionsRoute
  TenantSystemHealthRoute: typeof TenantSystemHealthRoute
  TenantTodayRoute: typeof TenantTodayRoute
  TenantWorkOrdersRoute: typeof TenantWorkOrdersRoute
  TenantOrdersIdRoute: typeof TenantOrdersIdRoute
  TenantOrdersNewRoute: typeof TenantOrdersNewRoute
  TenantPickupsNewRoute: typeof TenantPickupsNewRoute
  TenantStaffIdRoute: typeof TenantStaffIdRoute
  TenantStaffAttendanceRoute: typeof TenantStaffAttendanceRoute
  TenantStaffFairnessRoute: typeof TenantStaffFairnessRoute
  TenantStaffIroningPayrollRoute: typeof TenantStaffIroningPayrollRoute
  TenantStaffLeavesRoute: typeof TenantStaffLeavesRoute
  TenantStaffNewRoute: typeof TenantStaffNewRoute
  TenantStaffRequestsRoute: typeof TenantStaffRequestsRoute
  TenantStaffSalariesRoute: typeof TenantStaffSalariesRoute
  TenantStaffScheduleRoute: typeof TenantStaffScheduleRoute
  TenantStaffScorecardRoute: typeof TenantStaffScorecardRoute
  TenantStaffUsersRoute: typeof TenantStaffUsersRoute
  TenantStationsStageRoute: typeof TenantStationsStageRoute
  TenantStationsCleaningRoute: typeof TenantStationsCleaningRoute
  TenantStationsCsRoute: typeof TenantStationsCsRoute
  TenantStationsDeliveryRoute: typeof TenantStationsDeliveryRoute
  TenantStationsDryingAssemblyRoute: typeof TenantStationsDryingAssemblyRoute
  TenantStationsIntakeRoute: typeof TenantStationsIntakeRoute
  TenantStationsIroningRoute: typeof TenantStationsIroningRoute
  TenantStationsPackingRoute: typeof TenantStationsPackingRoute
  TenantStationsQcRoute: typeof TenantStationsQcRoute
  TenantStationsReceptionRoute: typeof TenantStationsReceptionRoute
  TenantStationsSortingRoute: typeof TenantStationsSortingRoute
  TenantOrdersIndexRoute: typeof TenantOrdersIndexRoute
  TenantPickupsIndexRoute: typeof TenantPickupsIndexRoute
  TenantStaffIndexRoute: typeof TenantStaffIndexRoute
}

const TenantRouteChildren: TenantRouteChildren = {
  TenantAccountingRoute: TenantAccountingRoute,
  TenantBillingRoute: TenantBillingRoute,
  TenantBranchesRoute: TenantBranchesRouteWithChildren,
  TenantBudgetsRoute: TenantBudgetsRoute,
  TenantCashClosingRoute: TenantCashClosingRoute,
  TenantCrmRoute: TenantCrmRoute,
  TenantCsRoute: TenantCsRoute,
  TenantCustomerCareRoute: TenantCustomerCareRoute,
  TenantCustomersRoute: TenantCustomersRoute,
  TenantDailyOperationsRoute: TenantDailyOperationsRoute,
  TenantDashboardRoute: TenantDashboardRoute,
  TenantDemoRoute: TenantDemoRoute,
  TenantDriverRoute: TenantDriverRoute,
  TenantExecutiveRoute: TenantExecutiveRoute,
  TenantFinanceRoute: TenantFinanceRoute,
  TenantHelpRoute: TenantHelpRoute,
  TenantInventoryRoute: TenantInventoryRoute,
  TenantIssuesRoute: TenantIssuesRoute,
  TenantLedgerRoute: TenantLedgerRoute,
  TenantLegalRoute: TenantLegalRoute,
  TenantLiveMapRoute: TenantLiveMapRoute,
  TenantManagerRoute: TenantManagerRoute,
  TenantMarketingRoute: TenantMarketingRoute,
  TenantMarketplaceRoute: TenantMarketplaceRoute,
  TenantOnboardingRoute: TenantOnboardingRoute,
  TenantOpsRoute: TenantOpsRoute,
  TenantReceivablesRoute: TenantReceivablesRoute,
  TenantReportsRoute: TenantReportsRouteWithChildren,
  TenantSearchRoute: TenantSearchRoute,
  TenantServicesRoute: TenantServicesRoute,
  TenantSettingsRoute: TenantSettingsRouteWithChildren,
  TenantSubscriptionsRoute: TenantSubscriptionsRoute,
  TenantSystemHealthRoute: TenantSystemHealthRoute,
  TenantTodayRoute: TenantTodayRoute,
  TenantWorkOrdersRoute: TenantWorkOrdersRoute,
  TenantOrdersIdRoute: TenantOrdersIdRoute,
  TenantOrdersNewRoute: TenantOrdersNewRoute,
  TenantPickupsNewRoute: TenantPickupsNewRoute,
  TenantStaffIdRoute: TenantStaffIdRoute,
  TenantStaffAttendanceRoute: TenantStaffAttendanceRoute,
  TenantStaffFairnessRoute: TenantStaffFairnessRoute,
  TenantStaffIroningPayrollRoute: TenantStaffIroningPayrollRoute,
  TenantStaffLeavesRoute: TenantStaffLeavesRoute,
  TenantStaffNewRoute: TenantStaffNewRoute,
  TenantStaffRequestsRoute: TenantStaffRequestsRoute,
  TenantStaffSalariesRoute: TenantStaffSalariesRoute,
  TenantStaffScheduleRoute: TenantStaffScheduleRoute,
  TenantStaffScorecardRoute: TenantStaffScorecardRoute,
  TenantStaffUsersRoute: TenantStaffUsersRoute,
  TenantStationsStageRoute: TenantStationsStageRoute,
  TenantStationsCleaningRoute: TenantStationsCleaningRoute,
  TenantStationsCsRoute: TenantStationsCsRoute,
  TenantStationsDeliveryRoute: TenantStationsDeliveryRoute,
  TenantStationsDryingAssemblyRoute: TenantStationsDryingAssemblyRoute,
  TenantStationsIntakeRoute: TenantStationsIntakeRoute,
  TenantStationsIroningRoute: TenantStationsIroningRoute,
  TenantStationsPackingRoute: TenantStationsPackingRoute,
  TenantStationsQcRoute: TenantStationsQcRoute,
  TenantStationsReceptionRoute: TenantStationsReceptionRoute,
  TenantStationsSortingRoute: TenantStationsSortingRoute,
  TenantOrdersIndexRoute: TenantOrdersIndexRoute,
  TenantPickupsIndexRoute: TenantPickupsIndexRoute,
  TenantStaffIndexRoute: TenantStaffIndexRoute,
}

const TenantRouteWithChildren =
  TenantRoute._addFileChildren(TenantRouteChildren)

interface AdminRouteChildren {
  AdminAdminBillingRoute: typeof AdminAdminBillingRoute
  AdminAdminBizDevRoute: typeof AdminAdminBizDevRoute
  AdminAdminBusinessPlanRoute: typeof AdminAdminBusinessPlanRoute
  AdminAdminCustomerSuccessRoute: typeof AdminAdminCustomerSuccessRoute
  AdminAdminDemoLibraryRoute: typeof AdminAdminDemoLibraryRoute
  AdminAdminInputBuilderRoute: typeof AdminAdminInputBuilderRoute
  AdminAdminInvestorRelationsRoute: typeof AdminAdminInvestorRelationsRoute
  AdminAdminLegalRoute: typeof AdminAdminLegalRoute
  AdminAdminMarketingPlanRoute: typeof AdminAdminMarketingPlanRoute
  AdminAdminPlatformBuilderRoute: typeof AdminAdminPlatformBuilderRoute
  AdminAdminPlatformFeesRoute: typeof AdminAdminPlatformFeesRoute
  AdminAdminReportBuilderRoute: typeof AdminAdminReportBuilderRoute
  AdminAdminTelemetryRoute: typeof AdminAdminTelemetryRoute
  AdminAdminTemplatesRoute: typeof AdminAdminTemplatesRoute
  AdminAdminWorkflowBuilderRoute: typeof AdminAdminWorkflowBuilderRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminTenantsIdRoute: typeof AdminAdminTenantsIdRoute
  AdminAdminTenantsIndexRoute: typeof AdminAdminTenantsIndexRoute
  AdminAdminUsersIndexRoute: typeof AdminAdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminBillingRoute: AdminAdminBillingRoute,
  AdminAdminBizDevRoute: AdminAdminBizDevRoute,
  AdminAdminBusinessPlanRoute: AdminAdminBusinessPlanRoute,
  AdminAdminCustomerSuccessRoute: AdminAdminCustomerSuccessRoute,
  AdminAdminDemoLibraryRoute: AdminAdminDemoLibraryRoute,
  AdminAdminInputBuilderRoute: AdminAdminInputBuilderRoute,
  AdminAdminInvestorRelationsRoute: AdminAdminInvestorRelationsRoute,
  AdminAdminLegalRoute: AdminAdminLegalRoute,
  AdminAdminMarketingPlanRoute: AdminAdminMarketingPlanRoute,
  AdminAdminPlatformBuilderRoute: AdminAdminPlatformBuilderRoute,
  AdminAdminPlatformFeesRoute: AdminAdminPlatformFeesRoute,
  AdminAdminReportBuilderRoute: AdminAdminReportBuilderRoute,
  AdminAdminTelemetryRoute: AdminAdminTelemetryRoute,
  AdminAdminTemplatesRoute: AdminAdminTemplatesRoute,
  AdminAdminWorkflowBuilderRoute: AdminAdminWorkflowBuilderRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminTenantsIdRoute: AdminAdminTenantsIdRoute,
  AdminAdminTenantsIndexRoute: AdminAdminTenantsIndexRoute,
  AdminAdminUsersIndexRoute: AdminAdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  TenantRoute: TenantRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  CustomerPortalRoute: CustomerPortalRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  JoinSlugRoute: JoinSlugRoute,
  TrackTokenRoute: TrackTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
