-- Fix duplicated cash withdrawals caused by payroll payment + expense_payment for auto payroll expenses.
-- Also make every tenant/new laundry have a default branch so multi-branch data stays under one tenant.

CREATE OR REPLACE FUNCTION public.sync_expense_financials(_expense_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  e record;
  cash_id uuid;
  exp_code text := '5100';
  liab_code text := '2000';
  has_payable_journal boolean := false;
  has_payroll_cash_payment boolean := false;
BEGIN
  SELECT * INTO e FROM public.expenses WHERE id = _expense_id;
  IF e.id IS NULL THEN RETURN; END IF;

  IF e.status = 'void' THEN
    UPDATE public.journal_entries
    SET status = 'void', updated_at = now()
    WHERE tenant_id = e.tenant_id
      AND source_id = e.id
      AND source_type IN ('expense_payable','expense_payment')
      AND status <> 'void';
    UPDATE public.cash_transactions
    SET status = 'void'
    WHERE tenant_id = e.tenant_id
      AND source_type = 'expense_payment'
      AND source_id = e.id
      AND status <> 'void';
    RETURN;
  END IF;

  PERFORM public.ensure_default_chart_accounts_for(e.tenant_id);
  cash_id := public.ensure_default_cash_account_for(e.tenant_id);

  IF e.category = 'salaries' THEN
    exp_code := '5000';
    liab_code := '2100';
  ELSIF e.category IN ('rent','water','electricity') THEN
    exp_code := '5200';
  END IF;

  SELECT EXISTS (
    SELECT 1 FROM public.journal_entries
    WHERE tenant_id = e.tenant_id
      AND source_type = 'expense_payable'
      AND source_id = e.id
      AND status <> 'void'
  ) INTO has_payable_journal;

  -- For payroll generated by payroll_lines, cash is moved by payroll_payment.
  -- Do not also create expense_payment cash transaction.
  SELECT EXISTS (
    SELECT 1
    FROM public.cash_transactions ct
    WHERE ct.tenant_id = e.tenant_id
      AND ct.source_type = 'payroll_payment'
      AND ct.source_id = e.source_id
      AND ct.status = 'posted'
  ) INTO has_payroll_cash_payment;

  IF e.status = 'payable' THEN
    PERFORM public.create_journal_entry_for_tenant(e.tenant_id, COALESCE(e.spent_at, now())::date, COALESCE(e.description,'مصروف مستحق'), 'expense_payable', e.id,
      jsonb_build_array(
        jsonb_build_object('account_code', exp_code, 'debit', e.amount, 'credit', 0, 'memo', 'إثبات المصروف مرة واحدة'),
        jsonb_build_object('account_code', liab_code, 'debit', 0, 'credit', e.amount, 'memo', 'مصروف مستحق / آجل')
      )
    );
    RETURN;
  END IF;

  IF e.status = 'paid' THEN
    IF NOT has_payroll_cash_payment THEN
      INSERT INTO public.cash_transactions(tenant_id, cash_account_id, direction, amount, source_type, source_id, description, happened_at)
      VALUES (e.tenant_id, cash_id, 'out', e.amount, 'expense_payment', e.id, COALESCE(e.description,'مصروف'), COALESCE(e.paid_at, e.spent_at, now()))
      ON CONFLICT (tenant_id, source_type, source_id, direction)
        WHERE source_type IS NOT NULL AND source_id IS NOT NULL AND status <> 'void'
      DO NOTHING;
    ELSE
      UPDATE public.cash_transactions
      SET status = 'void'
      WHERE tenant_id = e.tenant_id
        AND source_type = 'expense_payment'
        AND source_id = e.id
        AND status <> 'void';
    END IF;

    IF has_payable_journal THEN
      PERFORM public.create_journal_entry_for_tenant(e.tenant_id, COALESCE(e.paid_at, e.spent_at, now())::date, 'سداد ' || COALESCE(e.description,'مصروف مستحق'), 'expense_payment', e.id,
        jsonb_build_array(
          jsonb_build_object('account_code', liab_code, 'debit', e.amount, 'credit', 0, 'memo', 'إقفال المصروف المستحق'),
          jsonb_build_object('account_code', '1000', 'debit', 0, 'credit', e.amount, 'memo', 'صرف من الخزنة')
        )
      );
    ELSE
      PERFORM public.create_journal_entry_for_tenant(e.tenant_id, COALESCE(e.spent_at, now())::date, COALESCE(e.description,'مصروف مدفوع'), 'expense_payment', e.id,
        jsonb_build_array(
          jsonb_build_object('account_code', exp_code, 'debit', e.amount, 'credit', 0, 'memo', 'مصروف مدفوع مباشرة'),
          jsonb_build_object('account_code', '1000', 'debit', 0, 'credit', e.amount, 'memo', 'صرف من الخزنة')
        )
      );
    END IF;
  END IF;
END;
$$;
GRANT EXECUTE ON FUNCTION public.sync_expense_financials(uuid) TO authenticated;

-- Void historical duplicate expense_payment cash transactions for payroll lines when payroll_payment already exists.
UPDATE public.cash_transactions ct
SET status = 'void'
FROM public.expenses e
WHERE ct.tenant_id = e.tenant_id
  AND ct.source_type = 'expense_payment'
  AND ct.source_id = e.id
  AND ct.status <> 'void'
  AND e.source_type = 'auto_payroll_line'
  AND EXISTS (
    SELECT 1
    FROM public.cash_transactions pt
    WHERE pt.tenant_id = e.tenant_id
      AND pt.source_type = 'payroll_payment'
      AND pt.source_id = e.source_id
      AND pt.status = 'posted'
  );

-- Recalculate balances after voiding duplicate cash withdrawals.
DO $$
DECLARE r record;
BEGIN
  FOR r IN SELECT id FROM public.expenses WHERE status IN ('paid','payable') LOOP
    PERFORM public.sync_expense_financials(r.id);
  END LOOP;

  FOR r IN SELECT DISTINCT tenant_id FROM public.cash_accounts LOOP
    -- cannot use current_tenant_id in service context, so set exact current_balance per account explicitly.
    UPDATE public.cash_accounts ca
    SET current_balance = public.cash_account_expected_balance(ca.id), updated_at = now()
    WHERE ca.tenant_id = r.tenant_id;
  END LOOP;
END $$;

-- Branch model: one laundry/company can have many branches under the same tenant.
-- Ensure every tenant has a default branch.
CREATE OR REPLACE FUNCTION public.ensure_default_branch_for(_tenant_id uuid, _tenant_name text DEFAULT NULL)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE bid uuid;
BEGIN
  SELECT id INTO bid
  FROM public.branches
  WHERE tenant_id = _tenant_id AND name = 'الفرع الرئيسي'
  LIMIT 1;

  IF bid IS NULL THEN
    INSERT INTO public.branches(tenant_id, name, is_active)
    VALUES (_tenant_id, 'الفرع الرئيسي', true)
    RETURNING id INTO bid;
  END IF;

  RETURN bid;
END;
$$;
GRANT EXECUTE ON FUNCTION public.ensure_default_branch_for(uuid,text) TO authenticated;

CREATE OR REPLACE FUNCTION public.seed_tenant_defaults(_tenant_id uuid, _tenant_name text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.app_settings (tenant_id, business_name)
  VALUES (_tenant_id, COALESCE(_tenant_name, 'مغسلة'))
  ON CONFLICT (tenant_id) DO NOTHING;

  PERFORM public.ensure_default_branch_for(_tenant_id, _tenant_name);
  PERFORM public.ensure_default_cash_account_for(_tenant_id);
  PERFORM public.ensure_default_chart_accounts_for(_tenant_id);

  INSERT INTO public.service_items (tenant_id, name, service_type, unit_price, is_active, category_id)
  SELECT _tenant_id, x.name, x.service_type, x.unit_price, x.is_active, NULL
  FROM (
    SELECT DISTINCT ON (name) name, service_type, unit_price, is_active
    FROM public.service_items
    WHERE tenant_id IS NOT NULL AND tenant_id <> _tenant_id
    ORDER BY name, created_at DESC
  ) x
  WHERE NOT EXISTS (
    SELECT 1 FROM public.service_items s WHERE s.tenant_id = _tenant_id AND s.name = x.name
  );

  INSERT INTO public.service_areas (tenant_id, name, area_type, aliases, lat, lng, default_delivery_fee, is_active, notes)
  SELECT _tenant_id, x.name, x.area_type, x.aliases, x.lat, x.lng, x.default_delivery_fee, x.is_active, x.notes
  FROM (
    SELECT DISTINCT ON (name) name, area_type, aliases, lat, lng, default_delivery_fee, is_active, notes, created_at
    FROM public.service_areas
    WHERE tenant_id IS NOT NULL AND tenant_id <> _tenant_id
    ORDER BY name, created_at DESC
  ) x
  WHERE NOT EXISTS (
    SELECT 1 FROM public.service_areas a WHERE a.tenant_id = _tenant_id AND a.name = x.name
  );
END;
$$;

DO $$
DECLARE r record;
BEGIN
  FOR r IN SELECT id, name FROM public.tenants LOOP
    PERFORM public.seed_tenant_defaults(r.id, r.name);
  END LOOP;
END $$;
